// FAO : posages + parcours 2.5D + post-processeurs Siemens 840D / Fagor 8065.
// Pur logique (aucun OCCT) : modèle posage, origine G54, générateurs,
// post-pros, arbre FAO, fiches panneau droit, persistance — sans rejeu.
const {loadApp}=require('./appvm.cjs');
const vm=require('vm');
(async()=>{
  const {ctx}=loadApp();
  const R=[
    "const P=[];const p=s=>P.push(String(s));",
    "const ATT=[];const att=(ok,msg)=>{if(!ok)ATT.push(msg);};",
    // --- formats
    "att(faoFmtXYZ(10)==='10.000','fmt XYZ entier : '+faoFmtXYZ(10));",
    "att(faoFmtXYZ(12.34567)==='12.346','fmt XYZ arrondi : '+faoFmtXYZ(12.34567));",
    "att(faoFmtF(1200)==='1200.0','fmt feed : '+faoFmtF(1200));",
    "att(faoProgName('ma piece!')==='MA_PIECE_','prog name : '+faoProgName('ma piece!'));",
    // --- niveaux
    "const lv=faoLevels(25,0,10);",
    "att(JSON.stringify(lv)===JSON.stringify([15,5,0]),'niveaux 25->0 ap10 : '+JSON.stringify(lv));",
    // --- racine posages
    "const rt0=faoRoot();",
    "att(rt0.setups.length===1&&rt0.activeSetupId===rt0.setups[0].id,'root : 1 posage actif');",
    "att(faoSetup().machine==='siemens630','setup defaut : machine 630');",
    // --- job de test
    "const job=faoDefaultJob();job.name='TEST';job.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "job.ops=[{type:'facing',z:25,ae:6},{type:'pocket',x0:10,y0:10,x1:90,y1:70,ztop:25,zbot:5,ap:10,ae:5},{type:'contour',x0:10,y0:10,x1:90,y1:70,ztop:5,zbot:0,ap:5},{type:'drill',pts:[[20,20],[80,60]],ztop:25,zbot:5}];",
    // --- surfaçage
    "const f=faoOpMoves(job.ops[0],job);",
    "att(f.length>10,'facing : '+f.length+' moves');",
    "att(f[0].r===1,'facing : 1er move rapide');",
    "att(f.filter(m=>!m.r).every(m=>Math.abs(m.z-25)<1e-9),'facing : toute la coupe à Z=25');",
    "att(f.every(m=>m.y>=-5.01&&m.y<=85.01),'facing : Y dans [y0-r,y1+r]');",
    "att(f.filter(m=>m.r).every(m=>m.z>=25-1e-9),'facing : rapides au-dessus du brut (Z>=25)');",
    // --- poche
    "const pk=faoOpMoves(job.ops[1],job);",
    "att(pk.length>20,'pocket : '+pk.length+' moves');",
    "att(pk.every(m=>m.x>=9.99&&m.x<=90.01&&m.y>=9.99&&m.y<=70.01),'pocket : XY dans le rectangle');",
    "att(pk.some(m=>!m.r&&Math.abs(m.z-5)<1e-9),'pocket : fond Z=5 atteint');",
    // --- contour
    "const ct=faoOpMoves(job.ops[2],job);",
    "att(ct.length>0,'contour : moves');",
    "att(ct.some(m=>!m.r&&Math.abs(m.x-95)<1e-9),'contour : compensation +r (x1+D/2=95)');",
    "att(ct.filter(m=>!m.r).every(m=>Math.abs(m.z-0)<1e-9),'contour : 1 niveau Z=0 (5->0 ap5)');",
    // --- perçage
    "const dr=faoOpMoves(job.ops[3],job);",
    "att(dr.length===8,'drill 2 trous : 8 moves, vu '+dr.length);",
    "att(dr.filter(m=>!m.r).every(m=>Math.abs(m.z-5)<1e-9),'drill : fond Z=5');",
    // --- estimation
    "const e=faoEstimate(f,faoToolSF(job.tools[0]).f,5000);",
    "att(e.cut>0&&e.tmin>0,'estimation : cut='+e.cut.toFixed(0)+' t='+e.tmin.toFixed(2));",
    // --- post Siemens 630
    "const s630=faoPost(job,'siemens630');",
    "att(s630.ext==='mpf','siemens ext mpf');",
    "att(s630.code.indexOf('; %_N_TEST_MPF')===0,'siemens : en-tete %_N_');",
    "att(/G71/.test(s630.code)&&/G17 G90 G94 G54/.test(s630.code),'siemens : G71/G17/G90/G94/G54');",
    "att(/\\nT1 D1\\n/.test(s630.code),'siemens : appel outil T1 D1');",
    "att(/X-200/.test(s630.code),'siemens630 : parc X-200');",
    "att(/M30/.test(s630.code),'siemens : M30');",
    "att(!/^N[0-9]+ /m.test(s630.code),'siemens : pas de numeros de sequence');",
    "att((s630.code.match(/\\nG1 /g)||[]).length>20,'siemens : G1 bien presents');",
    // --- variante 1520 : seul le parc change
    "const s1520=faoPost(job,'siemens1520');",
    "att(/X-430/.test(s1520.code),'siemens1520 : parc X-430');",
    "att(s1520.code.replace(/X-430/g,'X-200').replace(/1520/g,'630')===s630.code,'1520 vs 630 : seule difference = parc X (+ nom en-tete)');",
    // --- post Fagor 8065
    "const fg=faoPost(job,'fagor8065');",
    "att(fg.ext==='nc','fagor ext nc');",
    "att(/^\\(TEST/.test(fg.code),'fagor : commentaire (NOM ...)');",
    "att(/M06/.test(fg.code)&&/M03/.test(fg.code),'fagor : M06/M03');",
    "att(/^N10 /m.test(fg.code),'fagor : sequences des N10');",
    "att(/M30/.test(fg.code),'fagor : M30');",
    "att((fg.code.match(/ G1 /g)||[]).length===(s630.code.match(/\\nG1 /g)||[]).length,'fagor/siemens : meme nombre de G1');",
    "att(fg.code.indexOf('SUPA')<0,'fagor : pas de SUPA (inconnu sur Fagor)');",
    // --- parité des avances (plongée Fagor = plongée Siemens, jamais sur un XY seul)
    "const sfp=faoFmtF(faoToolSF(job.tools[0]).plunge),fsCut=faoFmtF(faoToolSF(job.tools[0]).f);",
    "const fsS=(s630.code.match(/ F[0-9.]+/g)||[]).join(','),fsF=(fg.code.match(/ F[0-9.]+/g)||[]).join(',');",
    "att(fsS===fsF,'fagor/siemens : meme sequence d avances F ('+fsS.length+' mots)');",
    "const badPl=(fg.code.match(/\\nN[0-9]+ G1 [^\\n]*/g)||[]).filter(l=>l.indexOf(' F'+sfp)>=0&&l.indexOf('Z')<0);",
    "att(sfp===fsCut||badPl.length===0,'fagor : F plongee jamais sur un XY seul (vu '+badPl.length+')');",
    // --- P0-4 : G40/G80 en entête + garde-fou « coupe sous le brut »
    "att(/G40 G80 G17 G90 G94 G54/.test(s630.code),'siemens : G40 G80 en entete');",
    "att(/G40 G80 G17/.test(fg.code),'fagor : G40 G80 en entete');",
    "att(s630.warns&&s630.warns.length===0,'job normal : aucune alerte sous le brut');",
    "const jobZ=faoDefaultSetup();jobZ.name='ZTEST';jobZ.stock={x0:0,y0:0,z0:0,x1:50,y1:50,z1:10};",
    "jobZ.ops=[{id:'z1',on:true,toolId:'T1',type:'drill',pts:[[25,25]],ztop:10,zbot:-3}];",
    "const gz=faoPost(jobZ,'siemens630');",
    "att(gz.warns&&gz.warns.length===1,'garde-fou : 1 alerte sous le brut ('+(gz.warns||[]).join('|')+')');",
    "att(/ATTENTION/.test(gz.code)&&/sous le brut/.test(gz.code),'garde-fou : mentionnee dans le G-code');",
    "const gzF=faoPost(jobZ,'fagor8065');",
    "att(gzF.warns.length===1&&/\\( ATTENTION/.test(gzF.code),'garde-fou fagor : ( ATTENTION ... )');",
    "att(/CYCLE81/.test(gz.code),'garde-fou : per\\u00e7age alarm\\u00e9 reste en cycle');",
    // --- P1-a : cycles de per\\u00e7age dialecte (golden tests)
    "att(/CYCLE81\\(5\\.000, 0\\.000, 5\\.000, -20\\.000, \\)/.test(s630.code),'siemens : CYCLE81 (golden)');",
    "att(!/CYCLE83/.test(s630.code),'sans Q : pas de CYCLE83');",
    "att(/G0 X20\\.000 Y20\\.000 Z5\\.000 F/.test(s630.code),'siemens : trou au retrait, F plong\\u00e9e sur le G0');",
    "att(/G98 G81 X20\\.000 Y20\\.000 Z5\\.000 I-20\\.000/.test(fg.code),'fagor : G98 G81 (golden)');",
    "att(/G80/.test(fg.code),'fagor : G80 annule le cycle');",
    "att(!/G83/.test(fg.code),'sans Q : pas de G83 fagor');",
    // --- P1-a : broche \\u00e0 va-et-vient (Q / peck)
    "const jobPk=faoDefaultSetup();jobPk.name='PK';jobPk.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobPk.ops=[{id:'k1',on:true,toolId:'T1',type:'drill',pts:[[20,20],[80,60]],ztop:25,zbot:5,peck:4}];",
    "const spk=faoPost(jobPk,'siemens630').code;",
    "att(/CYCLE83\\(5\\.000, 0\\.000, 5\\.000, -20\\.000, , -4\\.000/.test(spk),'siemens : CYCLE83 Q=4 (golden, FDEP=RFP-Q)');",
    "att(!/CYCLE81\\(/.test(spk),'Q>0 : CYCLE81 remplac\\u00e9 par CYCLE83');",
    "const fpk=faoPost(jobPk,'fagor8065').code;",
    "att(/G98 G83 X20\\.000 Y20\\.000 Z5\\.000 I-4\\.000 J5/.test(fpk),'fagor : G83 I=-4 J=5 (golden)');",
    "att(!/G81 X/.test(fpk),'Q>0 fagor : G81 remplac\\u00e9 par G83');",
    // --- bibliothèque : Vc/fz -> S/F
    "const sf=faoToolSF({d:10,vc:250,fz:0.06,flutes:2});",
    "att(sf.s===7958&&sf.f===955,'biblio Vc250/fz0.06 D10 : S'+sf.s+' F'+sf.f);",
    // --- rapide machine + plongée % (P0-3)
    "att(faoRapide(job)===5000&&faoPlungePct(job)===30,'defauts posage : rapide 5000 + plongee 30 %');",
    "const sfP50=faoToolSF(job.tools[0],{plungePct:50});",
    "att(sfP50.plunge===Math.max(1,Math.round(sfP50.f*0.5)),'plongee 50 % de F : '+sfP50.plunge);",
    "const jobPl50=faoDefaultSetup();jobPl50.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};jobPl50.plungePct=50;",
    "jobPl50.ops=[{id:'p1',on:true,toolId:'T1',type:'drill',pts:[[20,20]],ztop:25,zbot:5}];",
    "const fp50=faoFmtF(faoToolSF(jobPl50.tools[0],jobPl50).plunge),fp30=faoFmtF(faoToolSF(jobPl50.tools[0],{plungePct:30}).plunge);",
    "att(fp50!==fp30,'50 % != 30 % ('+fp50+' vs '+fp30+')');",
    "const gP=faoPost(jobPl50,'siemens630').code;",
    "att(gP.indexOf(' F'+fp50)>=0,'post : plongee 50 % emise ('+fp50+')');",
    "att(gP.indexOf(' F'+fp30)<0,'post : plongee 30 % absente');",
    // --- multi-outils : 2 groupes, 2 changements
    "const jobB=faoDefaultJob();jobB.name='BI';jobB.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobB.ops=[{id:'a',on:true,toolId:'T1',type:'facing',z:25,ae:6},{id:'b',on:true,toolId:'T2',type:'facing',z:25,ae:4}];",
    "att(faoJobMoves(jobB).length===2,'multi-outils : 2 groupes');",
    "const sbi=faoPost(jobB,'siemens630').code;",
    "att((sbi.match(/\\nM6\\n/g)||[]).length===2,'multi-outils : 2x M6');",
    "att(/T2 D1/.test(sbi),'multi-outils : appel T2 D1');",
    // --- laisse ébauche
    "const cl=faoGenContour({x0:10,y0:10,x1:90,y1:70},5,0,{toolD:10,secu:30,laisse:0.5});",
    "att(cl.some(m=>!m.r&&Math.abs(m.x-95.5)<1e-9),'contour laisse 0.5 : X max 95.5');",
    "att(cl.filter(m=>!m.r).every(m=>m.z>=0.5-1e-9),'contour laisse 0.5 : fond Z>=0.5');",
    "const pl=faoGenPocket({x0:10,y0:10,x1:90,y1:70},25,5,{toolD:10,secu:30,ap:10,ae:5,laisse:0.5});",
    "att(pl.filter(m=>!m.r).every(m=>m.z>=5.5-1e-9),'poche laisse 0.5 : fond Z>=5.5');",
    // --- op désactivée ignorée partout
    "const jobC=JSON.parse(JSON.stringify(jobB));jobC.ops[0].on=false;",
    "att(faoJobMoves(jobC).length===1,'off : 1 seul groupe actif');",
    "doc.fao=jobC;",
    "att(faoStatsText().indexOf('1 op')===0,'off : stats 1 op active ('+faoStatsText()+')');",
    "att(faoPost(jobC,'siemens630').code.indexOf('T1 D1')<0,'off : T1 absent du G-code');",
    // --- migration ancien job plat (outil unique, 31t)
    "const keepFao=doc.fao;",
    "doc.fao={name:'VIEUX',wcs:'G54',post:'siemens630',tool:{num:1,d:12,s:6000,f:900,plunge:200},coolant:'flood',secu:5,marge:5,stock:{x0:0,y0:0,z0:0,x1:50,y1:50,z1:10},ops:[{type:'facing',z:10,ae:6}]};",
    "const rtM=faoRoot();",
    "att(rtM.setups.length===1,'migration : 1 posage enveloppe');",
    "const mig=rtM.setups[0];",
    "att(mig.tools.length===1&&mig.tools[0].d===12,'migration : outil unique -> biblio D12');",
    "att(mig.machine==='siemens630','migration : post -> machine');",
    "att(mig.ops[0].toolId===mig.tools[0].id&&mig.ops[0].on===true&&!!mig.ops[0].id,'migration : op recoit id+toolId+on');",
    "doc.fao=keepFao;",
    // --- origine pièce : G-code relatif au point de bloc
    "const jobO=faoDefaultSetup();jobO.stock={x0:10,y0:0,z0:0,x1:110,y1:80,z1:25};",
    "jobO.ops=[{id:'o1',on:true,toolId:'T1',type:'facing',z:25,ae:6}];",
    "const so=faoPost(jobO,'siemens630').code;",
    "att(/X-7\\.000/.test(so),'origine : X relatif (10-7-10=-7)');",
    "att(/Z0\\.000/.test(so),'origine : Z relatif (25-25=0)');",
    "att(/Origine G54/.test(so),'origine : commentaire G54');",
    "jobO.origin={preset:'top-C'};",
    "att(/dessus centre/.test(faoPost(jobO,'siemens630').code),'origine : preset centre');",
    // --- machine portée par le posage
    "const jobM=faoDefaultSetup();jobM.machine='fagor8065';jobM.stock={x0:0,y0:0,z0:0,x1:50,y1:50,z1:10};",
    "jobM.ops=[{id:'m1',on:true,toolId:'T1',type:'facing',z:10,ae:6}];",
    "att(faoPost(jobM).ext==='nc','machine du posage : fagor -> nc sans forcer');",
    // --- arbre FAO dédié
    "doc.fao={setups:[job],activeSetupId:job.id};",
    "faoRoot();",
    "document.getElementById('faoTree').children.length=0;",
    "faoRenderTree();",
    "att(document.getElementById('faoTree').children.length===5,'arbre FAO : 1 posage + 4 ops');",
    // --- fiches dans le panneau droit
    "const sid=faoSetup().id, oid=faoSetup().ops[0].id;",
    "sel={kind:'faoOp',id:oid,setup:sid};renderProps();",
    "att(document.getElementById('props').children.length>2,'fiche op dans panneau droit');",
    "sel={kind:'faoSetup',id:sid};renderProps();",
    "att(document.getElementById('props').children.length>2,'fiche posage dans panneau droit');",
    // --- fiche Ébauche 3D : sections lisibles, sans plantage (3 stratégies)
    "const r3=faoOpDefaults('rough3d');",
    "const c3=faoOpCardElement(faoSetup(),r3,0);",
    "att(c3.children.length>8,'fiche ebauche 3D : sections, vu '+c3.children.length);",
    "r3.strategy='adaptive';r3.ae=6;const c3b=faoOpCardElement(faoSetup(),r3,0);",
    "att(c3b.children.length>8,'fiche adaptive + alerte ae : sans plantage');",
    "r3.strategy='zigzag';const c3c=faoOpCardElement(faoSetup(),r3,0);",
    "att(c3c.children.length>8,'fiche zigzag : sans plantage');",
    "sel={kind:null,id:null};",
    // --- surépaisseurs radiale / axiale séparées
    "const pr=faoGenPocket({x0:10,y0:10,x1:90,y1:70},25,5,{toolD:10,secu:30,ap:10,ae:5,radial:1,axial:0});",
    "att(pr.filter(m=>!m.r).every(m=>m.z>=5-1e-9),'poche A0 : fond Z=5');",
    "att(pr.every(m=>m.x>=10.99&&m.x<=89.01&&m.y>=10.99&&m.y<=69.01),'poche R1 : XY dans [11,89]x[11,69]');",
    "const cr=faoGenContour({x0:10,y0:10,x1:90,y1:70},5,0,{toolD:10,secu:30,radial:0.5,axial:0});",
    "att(cr.some(m=>!m.r&&Math.abs(m.x-95.5)<1e-9),'contour R0.5 : X max 95.5');",
    "att(cr.filter(m=>!m.r).every(m=>Math.abs(m.z-0)<1e-9),'contour A0 : fond Z=0');",
    // --- migration laisse -> R/A (géodésique garde laisse)
    "const mOP={type:'pocket',laisse:0.5};faoSanitiseOps({tools:[{id:'T1'}],ops:[mOP]});",
    "att(mOP.radial===0.5&&mOP.axial===0.5&&mOP.laisse===undefined,'migration laisse -> R/A');",
    "const mOG={type:'geofinish',laisse:0.5};faoSanitiseOps({tools:[{id:'T1'}],ops:[mOG]});",
    "att(mOG.laisse===0.5&&mOG.radial===undefined,'geodesique : laisse conservee');",
    // --- plan de retrait : défaut dessus+25, utilisé entre outils
    "att(faoRetractZ(job)===50,'retrait auto = z1+25');",
    "att(/G0 Z25\\.000/.test(sbi),'retrait inter-outils (50-25=25 relatif)');",
    "jobB.retract=60;",
    "att(/G0 Z35\\.000/.test(faoPost(jobB,'siemens630').code),'retrait manuel 60 -> Z35');",
    "delete jobB.retract;",
    // --- Liang-Barsky + clipping
    "const lb=faoClipLB({x:-10,y:5},{x:10,y:5},{x0:0,y0:0,x1:10,y1:10});",
    "att(lb&&Math.abs(lb[0]-0.5)<1e-9&&Math.abs(lb[1]-1)<1e-9,'Liang-Barsky : entree 0.5');",
    "att(faoClipLB({x:-5,y:-5},{x:-1,y:-1},{x0:0,y0:0,x1:10,y1:10})===null,'LB : dehors -> null');",
    "const ei=faoEffLimit({limit:{mode:'rect',x0:0,y0:0,x1:20,y1:20,side:'in',extra:0}},10);",
    "att(ei&&ei.x0===5&&ei.x1===15,'limite in : retractee de r=5');",
    "att(faoEffLimit({limit:{mode:'rect',x0:0,y0:0,x1:10,y1:10,side:'out',extra:1}},10).x0===-6,'limite out+extra : -6');",
    "const jobL=faoDefaultSetup();jobL.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobL.ops=[{id:'l1',on:true,toolId:'T1',type:'facing',z:25,ae:6,limit:{mode:'rect',x0:0,y0:0,x1:50,y1:80,side:'center',extra:0}}];",
    "const lc=faoOpMoves(jobL.ops[0],jobL).filter(m=>!m.r);",
    "att(lc.length>0&&lc.every(m=>m.x>=-1e-9&&m.x<=50+1e-9),'clip facing : coupe dans [0,50]');",
    "const jobD=faoDefaultSetup();",
    "att(faoLimitDrillPts({pts:[[5,5],[99,99]],limit:{mode:'rect',x0:0,y0:0,x1:10,y1:10,side:'center',extra:0}},10).length===1,'perçage : trou hors limite écarté');",
    // --- chaînes tangentes : A-B tangents, C perpendiculaire
    "const ED=[{pts:[[0,0,0],[10,0,0]]},{pts:[[10,0,0],[20,0,0]]},{pts:[[20,0,0],[20,10,0]]}];",
    "att(JSON.stringify(faoTangentSet(ED,[0]).sort())===JSON.stringify([0,1]),'tangent : A+B');",
    "att(JSON.stringify(faoTangentSet(ED,[2]))===JSON.stringify([2]),'tangent : C seule');",
    // --- ordonnancement + boucle XY fermée (carré 10x10 désordonné)
    "const SQ=[{pts:[[10,0,5],[10,10,5]]},{pts:[[0,0,5],[10,0,5]]},{pts:[[0,10,5],[0,0,5]]},{pts:[[10,10,5],[0,10,5]]}];",
    "const CH=faoOrderEdges(SQ,[0,1,2,3]);",
    "att(CH.length===1&&CH[0].length===4,'ordre : 1 chaîne de 4');",
    "const LP=faoLoopFromChains(SQ,CH);",
    "att(LP.closed===true,'boucle : fermée');",
    "att(Math.abs(faoLoopArea(LP.loop)-100)<0.01,'boucle : aire 100');",
    // --- impair + distance + règle outil
    "const CAR=[[20,20],[80,20],[80,80],[20,80],[20,20]];",
    "att(faoPointInPoly(50,50,CAR)===true&&faoPointInPoly(10,10,CAR)===false,'impair : dedans/dehors');",
    "att(Math.abs(faoDistToPoly(50,50,CAR)-30)<1e-9,'distance : 30 au bord');",
    "att(faoLimInside(50,50,{loop:CAR,side:'in',extra:0},5)===true,'in : centre à 30>=5');",
    "att(faoLimInside(77,50,{loop:CAR,side:'in',extra:0},5)===false,'in : à 3<5 écarté');",
    "att(faoLimInside(83,50,{loop:CAR,side:'out',extra:0},5)===true,'out : à 3<=5 gardé');",
    "att(faoLimInside(90,50,{loop:CAR,side:'out',extra:0},5)===false,'out : à 10>5 écarté');",
    "att(faoLimInside(83,50,{loop:CAR,side:'center',extra:0},5)===false,'center : dehors écarté');",
    // --- clip polygone sur balayage : coupe dans le carré, précision 0.1
    "const MV=[{r:1,x:0,y:50,z:30},{r:1,x:0,y:50,z:25},{r:0,x:100,y:50,z:25}];",
    "const MC=faoClipMovesPoly(MV,{loop:CAR,side:'center',extra:0},5,30,2);",
    "const MCC=MC.filter(m=>!m.r);",
    "att(MCC.length>0&&MCC.every(m=>m.x>=20-0.15&&m.x<=80+0.15),'clip poly : coupe dans [20,80] a 0.15 pres');",
    "att(MCC.some(m=>Math.abs(m.x-20)<0.11),'clip poly : entrée à 0.1 près');",
    "att(MC.some(m=>m.r&&m.z===30),'clip poly : ré-entrée par sécu');",
    // --- dispatch chaîne + filtre perçage chaîne
    "const jobH=faoDefaultSetup();jobH.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobH.ops=[{id:'h1',on:true,toolId:'T1',type:'facing',z:25,ae:80,limit:{mode:'chain',loop:CAR,closed:true,nEdges:4,tangent:false,side:'center',extra:0}}];",
    "const mh=faoOpMoves(jobH.ops[0],jobH).filter(m=>!m.r);",
    "att(mh.length>0&&mh.every(m=>m.x>=-1e-9&&m.x<=80+1e-9&&m.y>=-1e-9&&m.y<=80+1e-9),'dispatch chaîne : coupe dans le carré');",
    "att(faoLimitDrillPts({pts:[[50,50],[5,5]],limit:{mode:'chain',loop:CAR,closed:true,side:'center',extra:0}},10).length===1,'perçage chaîne : 1/2 gardé');",
    // --- débourrage poche : hélice + pleine + tours, fond à 0.5
    "const DP=faoGenPocketRough({x0:0,y0:0,x1:100,y1:60},30,0,{toolD:10,ap:6,tour:2,ae:5,radial:0.5,axial:0.5,secu:35});",
    "att(DP.length>50,'débourrage : '+DP.length+' moves');",
    "att(DP.some(m=>!m.r&&m.z>24&&m.z<30),'débourrage : descente hélice');",
    "att(DP.some(m=>!m.r&&Math.abs(m.z-24)<1e-9&&Math.abs(m.x-50)<6),'débourrage : pleine passe à 24');",
    "const T28=DP.filter(m=>!m.r&&Math.abs(m.z-28)<1e-9);",
    "att(T28.length>0,'débourrage : tour à 28');",
    "att(T28.every(m=>Math.abs(m.x-5.5)<0.2||Math.abs(m.x-94.5)<0.2||Math.abs(m.y-5.5)<0.2||Math.abs(m.y-54.5)<0.2||Math.hypot(m.x-50,m.y-30)<=8),'débourrage : tour = périmètre (+ descente hélice)');",
    "att(DP.filter(m=>!m.r).every(m=>m.z>=0.5-1e-9),'débourrage : fond à 0.5 mini');",
    "att(DP.filter(m=>!m.r).every(m=>m.x>=5.5-1e-9&&m.x<=94.5+1e-9),'débourrage : radial 0.5 tenu');",
    // --- dispatch + fiche par défaut
    "const jobPct=faoDefaultSetup();",
    "const opP=faoOpDefaults('pocket3d');",
    "att(opP.type==='pocket3d'&&opP.ap===6&&opP.tour===2,'défauts débourrage : ap6 tours2');",
    "att(Array.isArray(faoOpMoves(Object.assign({},opP,{x0:0,y0:0,x1:100,y1:60,ztop:30,zbot:0}),jobPct)),'dispatch pocket3d');",
    // --- entrée en arc paroi : tangence à +Y des deux côtés
    "const endTan=function(L){",
    "  const cx=L.move.arc.i+L.sx, cy=L.move.arc.j+L.move.y;",
    "  const ex=L.move.x-cx, ey=L.move.y-cy, r=Math.hypot(ex,ey);",
    "  if(L.move.arc.cw)return [ey/r,-ex/r];",
    "  return [-ey/r,ex/r];",
    "};",
    "const LA=faoLeadArc(10,5,6,5,true,0);",
    "att(LA&&LA.sx===10&&LA.move.arc.cw===true,'lead-in gauche : départ 10, G2');",
    "att(Math.abs(endTan(LA)[0])<1e-9&&Math.abs(endTan(LA)[1]-1)<1e-9,'lead-in gauche : tangent +Y');",
    "const RA2=faoLeadArc(2,5,6,5,false,0);",
    "att(RA2&&RA2.sx===2&&RA2.move.arc.cw===false,'lead-in droite : départ 2, G3');",
    "att(Math.abs(endTan(RA2)[0])<1e-9&&Math.abs(endTan(RA2)[1]-1)<1e-9,'lead-in droite : tangent +Y');",
    "att(faoLeadArc(6,5,6,5,true,0)===null,'lead-in : M sur le mur -> null');",
    // --- arrondi 2.5D : poche avec arrondi -> arcs, sans -> aucun
    "const jobA=faoDefaultSetup();jobA.stock={x0:0,y0:0,z0:0,x1:100,y1:60,z1:20};",
    "const opA={id:'pa',on:true,toolId:'T1',type:'pocket',x0:10,y0:10,x1:90,y1:50,ztop:20,zbot:15,ap:5,ae:5,radial:0,axial:0,arrondi:3};",
    "att(faoOpMoves(opA,jobA).some(m=>!m.r&&m.arc),'poche arrondi 3 : arcs');",
    "const opB=Object.assign({},opA,{id:'pb',arrondi:0});",
    "att(!faoOpMoves(opB,jobA).some(m=>!m.r&&m.arc),'poche arrondi 0 : aucun arc');",
    // --- arrondi : L 10x10 R2 -> droite + arc + droite, centre (8,2)
    "const RD=faoRoundPath([{x:0,y:0,z:0},{x:10,y:0,z:0},{x:10,y:10,z:0}],2);",
    "att(RD.length===4&&!RD[1].arc&&!!RD[2].arc&&!RD[3].arc,'arrondi : G1+arc+G1');",
    "att(Math.abs(RD[1].x-8)<1e-9&&Math.abs(RD[2].x-10)<1e-9&&Math.abs(RD[2].y-2)<1e-9,'arrondi : points tangents (8,0)->(10,2)');",
    "att(RD[2].arc.cw===false&&Math.abs(RD[2].arc.i-0)<1e-9&&Math.abs(RD[2].arc.j-2)<1e-9,'arrondi : G3 centre relatif (0,2)');",
    // --- aligné : pas d'arc
    "const RL=faoRoundPath([{x:0,y:0,z:0},{x:5,y:0,z:0},{x:10,y:0,z:0}],2);",
    "att(RL.every(m=>!m.arc),'aligné : aucun arc');",
    // --- émission G2/G3 (les 2 CN en IJK)
    "att(faoArcWords({x:10,y:2,z:0,arc:{i:0,j:2,cw:false}},0,0,0)==='G3 X10.000 Y2.000 Z0.000 I0.000 J2.000','G3 IJK');",
    "att(faoArcWords({x:10,y:2,z:0,arc:{i:0,j:2,cw:true}},0,0,0).indexOf('G2 ')===0,'G2 horaire');",
    // --- estimation d'arc : quart de cercle R2 = PI
    "const EA=faoEstimate([{r:1,x:2,y:0,z:0},{r:0,x:0,y:2,z:0,arc:{i:-2,j:0,cw:false}}],1200,5000);",
    "att(Math.abs(EA.cut-Math.PI)<0.01,'arc estimé PI : '+EA.cut.toFixed(3));",
    // --- subdivision aperçu : sur le cercle, du début à la fin
    "const AS=faoArcSegs({x:2,y:0,z:0},{x:0,y:2,z:0,arc:{i:-2,j:0,cw:false}});",
    "att(AS.length>4,'subdivision : '+AS.length+' pts');",
    "att(AS.every(q=>Math.abs(Math.hypot(q[0],q[1])-2)<1e-9),'subdivision : rayon 2');",
    "att(Math.abs(AS[AS.length-1][0]-0)<1e-9&&Math.abs(AS[AS.length-1][1]-2)<1e-9,'subdivision : finit en (0,2)');",
    // --- persistance + non-rejeu
    "doc.fao=job;",
    "att(serialise().indexOf('\"fao\"')>=0,'serialise : doc.fao persiste');",
    "const v0=_docVersion;faoTouch();",
    "att(_docVersion===v0,'faoTouch : _docVersion inchange (aucun rejeu geometrique)');",
    // --- annulation documentaire des mods FAO (P0-2) : snapshot avant mutation, restaure a l'identique
    "const j0=JSON.stringify(doc.fao);",
    "faoSnapshot('test undo FAO');",
    "const stU=faoRoot();stU.setups[0].ops.push(faoOpDefaults('facing'));faoTouch();",
    "att(JSON.stringify(doc.fao)!==j0,'undo FAO : mutation effectuee');",
    "att(docUndo()===true,'undo FAO : docUndo ok');",
    "att(JSON.stringify(doc.fao)===j0,'undo FAO : etat restaure bit a bit');",
    "att(docRedo()===true,'redo FAO : docRedo ok');",
    "att(JSON.stringify(doc.fao)!==j0,'redo FAO : mutation re-appliquee');",
    // --- estimation : le rapide du posage pilote le temps annonce (P0-3)
    "doc.fao={setups:[Object.assign(faoDefaultSetup(),{name:'RAPTEST',stock:{x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},rapide:500,ops:[{id:'dr1',on:true,toolId:'T1',type:'drill',pts:[[10,10],[90,70]],ztop:25,zbot:5}]})],activeSetupId:null};",
    "const stA=faoStatsText();",
    "faoSetup().rapide=1000000;const stB=faoStatsText();",
    "att(stA&&stB&&stA!==stB,'stats : rapide du posage pris en compte ('+stA+' | '+stB+')');",
    "att(faoRapide({rapide:0})===5000&&faoRapide(null)===5000,'faoRapide : repli 5000 si invalide');",
    // --- P1-c : estimation à 2 nouveaux paramètres (accélération + changement d'outil)
    "att(faoAccel({accel:2500})===2500,'accel : 2500 lu');",
    "att(faoAccel({})===1000&&faoAccel(null)===1000&&faoAccel({accel:-4})===1000,'accel : defaut 1000 si absent/invalide');",
    "att(faoToolChg({toolChg:45})===45,'ch. outil : 45 s lu');",
    "att(faoToolChg({})===30&&faoToolChg(null)===30&&faoToolChg({toolChg:-1})===30,'ch. outil : defaut 30 s si absent/invalide');",
    "const EAc=faoEstimate([{r:1,x:0,y:0,z:0},{r:1,x:100,y:0,z:0}],1200,5000,1000);",
    "const tTheo=100/5000+(5000/60)/1000/60;",
    "att(Math.abs(EAc.tmin-tTheo)<1e-9,'accel : t = d/v + v/A ('+EAc.tmin.toFixed(6)+' vs '+tTheo.toFixed(6)+')');",
    "const EAfast=faoEstimate([{r:1,x:0,y:0,z:0},{r:1,x:100,y:0,z:0}],1200,5000,100000);",
    "att(EAfast.tmin<EAc.tmin,'accel : A elevee -> temps plus court');",
    "const EAold=faoEstimate([{r:1,x:0,y:0,z:0},{r:1,x:100,y:0,z:0}],1200,5000);",
    "att(Math.abs(EAold.tmin-EAc.tmin)<1e-12,'accel : repli 1000 sans 4e argument');",
    "const jobTC=faoDefaultSetup();jobTC.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobTC.tools=[{id:'T1',num:1,d:10,vc:250,fz:0.06,flutes:2},{id:'T2',num:2,d:6,vc:200,fz:0.05,flutes:2}];",
    "jobTC.ops=[{id:'t1',on:true,toolId:'T1',type:'facing',z:25,ae:6},{id:'t2',on:true,toolId:'T2',type:'facing',z:25,ae:4}];",
    "const sTc0=faoStats(Object.assign({},jobTC,{toolChg:0}));",
    "const sTc2=faoStats(Object.assign({},jobTC,{toolChg:120}));",
    "att(sTc0.groups===2,'stats : 2 groupes outil (T1 puis T2)');",
    "att(Math.abs((sTc2.tmin-sTc0.tmin)-2)<1e-9,'stats : 1 changement x 120 s = +2 min ('+(sTc2.tmin-sTc0.tmin).toFixed(3)+')');",
    "att(sTc2.tchg===2&&sTc0.tchg===0,'stats : tchg expose pour les tests');",
    // --- P2 : indexation 3+2 MVP (table C + B) — TRAORI Siemens, alerte Fagor
    "att(faoOrient({}).b===0&&faoOrient({}).c===0&&faoOrient(null).b===0,'orient : defaut 0/0');",
    "att(faoOrient({orient:{b:45.5,c:-90.123456}}).c===-90.123,'orient : arrondi 0.001');",
    "att(faoOrientOn({orient:{b:0,c:0}})===false&&faoOrientOn({orient:{b:0,c:30}})===true,'orient : detection active');",
    "const job32=faoDefaultSetup();job32.name='T32';job32.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "job32.ops=[{id:'a32',on:true,toolId:'T1',type:'facing',z:25,ae:6}];",
    "job32.orient={b:45,c:0};",
    "const g32=faoPost(job32,'siemens630').code;",
    "att(/TRAORI\\(1\\)/.test(g32),'siemens 3+2 : TRAORI(1) emis');",
    "att(/G0 B45\\.000 C0\\.000/.test(g32),'siemens 3+2 : positionnement B/C');",
    "att(g32.indexOf('TRAORI(1)')>0&&g32.indexOf('TRAORI(1)')<g32.indexOf('T1 D1'),'siemens 3+2 : TRAORI avant l outil');",
    "att(g32.indexOf('TRAFOOF')>0&&g32.indexOf('TRAFOOF')<g32.indexOf('M30'),'siemens 3+2 : TRAFOOF avant M30');",
    "att(faoPost(job32,'siemens630').warns.length===0,'siemens 3+2 : aucune alerte (TRAORI natif)');",
    "const g32f=faoPost(job32,'fagor8065');",
    "att(!/G0 B/.test(g32f.code),'fagor 3 axes : aucun B/C emis');",
    "att(!/TRAORI\\(1\\)/.test(g32f.code),'fagor 3 axes : pas de TRAORI');",
    "att(g32f.warns.length===1&&/machine 3 axes/.test(g32f.warns[0])&&/IGNOR/.test(g32f.warns[0]),'fagor 3 axes : alerte warns (indexation ignoree)');",
    "att(/ATTENTION/.test(g32f.code)&&/\\( 3\\+2 :/.test(g32f.code)&&/NON command/.test(g32f.code),'fagor 3 axes : alerte + commentaire en tete');",
    "job32.orient={b:0,c:0};",
    "const g32z=faoPost(job32,'siemens630');",
    "att(!/TRAORI|TRAFOOF/.test(g32z.code)&&!/B45\\.000/.test(g32z.code),'orient 0/0 : aucune trace 3+2');",
    "att(g32z.warns.length===0,'orient 0/0 : aucune alerte');",
    "delete job32.orient;const cAbs=faoPost(job32,'siemens630').code;job32.orient={b:0,c:0};",
    "att(cAbs===faoPost(job32,'siemens630').code,'orient 0/0 : programme identique a orient absent');",
    // --- P2 : rang 3+2 dans la fiche posage (saisie C + reset 3 axes)
    "const pc32=document.createElement('div');faoSetupFiche(pc32,faoSetup());",
    "let r32t=null;pc32.children.forEach(function(c){if(c.children&&c.children.length&&c.children[0].textContent==='3+2 B')r32t=c;});",
    "att(!!r32t,'UI fiche posage : rang 3+2 B/C');",
    "r32t.children[3].value='30';r32t.children[3].onchange();",
    "att(faoOrientOn(faoSetup())&&faoOrient(faoSetup()).c===30,'UI 3+2 : C=30 saisi');",
    "r32t.children[5].onclick();",
    "att(faoOrientOn(faoSetup())===false,'UI 3+2 : bouton 3 axes remet a plat');",
    // --- P2 : rejeu auto de la limite « chaîne » (ancres germes + stale)
    "const ceOp=faoSetup().ops[0];",
    "const ceMk=function(x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1;return {mid:[(x1+x2)/2,(y1+y2)/2,0],pts:[[x1,y1,0],[x2,y2,0]],len:Math.hypot(dx,dy),sharp:true};};",
    "const ceE=[ceMk(0,0,40,0),ceMk(40,0,40,30),ceMk(40,30,0,30),ceMk(0,30,0,0)];",
    "faoChainMode={setupId:faoSetup().id,opId:ceOp.id,edges:ceE,seeds:[0,1,2,3],tangent:false,sel:[0,1,2,3]};",
    "faoChainOk();",
    "att(ceOp.limit&&ceOp.limit.mode==='chain'&&ceOp.limit.anchors&&ceOp.limit.anchors.length===4,'capture chaine : 4 ancres sur les germes');",
    "att(ceOp.limit.stale===false,'capture chaine : stale=false');",
    "const ceL0=JSON.stringify(ceOp.limit.loop);",
    "att(faoLoopArea(ceOp.limit.loop)>1000,'capture chaine : boucle carree ~1200');",
    // (a) translation XY dans la tolérance -> la boucle suit
    "const ceE2=ceE.map(function(e){return {mid:[e.mid[0]+5,e.mid[1]-3,0],pts:e.pts.map(function(p){return [p[0]+5,p[1]-3,0];}),len:e.len,sharp:true};});",
    "const ceR1=faoChainRematch(ceOp,ceE2);",
    "att(ceR1.changed&&ceR1.stale===false&&ceR1.matched===4,'rejeu : 4/4 ancrees, boucle suivie');",
    "att(Math.abs(ceOp.limit.loop[0][0]-(JSON.parse(ceL0)[0][0]+5))<1e-6&&Math.abs(ceOp.limit.loop[0][1]-(JSON.parse(ceL0)[0][1]-3))<1e-6,'rejeu : boucle translatee (+5,-3)');",
    // (b) changement de Z seul -> XY identique -> pas de changement
    "const ceE3=ceE2.map(function(e){return {mid:[e.mid[0],e.mid[1],20],pts:e.pts.map(function(p){return [p[0],p[1],20];}),len:e.len,sharp:true};});",
    "const ceL1=JSON.stringify(ceOp.limit.loop);",
    "const ceR2=faoChainRematch(ceOp,ceE3);",
    "att(ceR2.changed===false&&ceR2.stale===false&&ceR2.matched===4,'rejeu : Z seul, boucle XY inchangee');",
    // (c) deplacement hors tolérance -> stale, boucle figee conservee
    "const ceE4=ceE.map(function(e){return {mid:[e.mid[0]+50,e.mid[1],0],pts:e.pts.map(function(p){return [p[0]+50,p[1],0];}),len:e.len,sharp:true};});",
    "const ceR3=faoChainRematch(ceOp,ceE4);",
    "att(ceR3.changed&&ceOp.limit.stale===true&&JSON.stringify(ceOp.limit.loop)===ceL1,'rejeu : +50 mm hors tol -> stale + boucle figee');",
    // (d) retour du modele d origine -> stale leve, boucle revenue
    "const ceR4=faoChainRematch(ceOp,ceE);",
    "att(ceR4.changed&&ceOp.limit.stale===false&&JSON.stringify(ceOp.limit.loop)===ceL0,'rejeu : retour modele -> stale leve + boucle restauree');",
    // (e) arete manquante -> tous les germes requis -> stale
    "const ceR5=faoChainRematch(ceOp,ceE.slice(0,3));",
    "att(ceR5.changed&&ceOp.limit.stale===true&&JSON.stringify(ceOp.limit.loop)===ceL0,'rejeu : arete disparue -> stale, boucle figee');",
    // (f) ancien document sans ancres -> ignore (comportement historique)
    "ceOp.limit={mode:'chain',loop:JSON.parse(ceL0),closed:true,nEdges:4,tangent:false,side:'center',extra:0};",
    "const ceR6=faoChainRematch(ceOp,ceE);",
    "att(ceR6.changed===false&&ceR6.skipped===true&&JSON.stringify(ceOp.limit.loop)===ceL0,'rejeu : sans ancres -> ignore');",
    // (g) tangente re-deduite depuis le germe (3 segments colineaires), boucle degeneree -> stale
    "const ceC=[ceMk(0,0,10,0),ceMk(10,0,20,0),ceMk(20,0,30,0)];",
    "ceOp.limit={mode:'chain',loop:[[0,0],[10,0]],closed:false,nEdges:1,tangent:true,side:'center',extra:0,anchors:[{m:[5,0,0],len:10}]};",
    "const ceR7=faoChainRematch(ceOp,ceC);",
    "att(ceR7.nSel===3&&ceR7.stale===true,'rejeu : tangent re-derinee (3) + boucle degeneree -> stale');",
    // (h) replay sans OCCT/solide exact -> no-op garde
    "att(faoChainReplay()===0,'rejeu : solide exact absent -> replay no-op (0)');",
    // (h2) câblage : la fin de rejeu (buildDone) appelle faoChainReplay
    "let ceBd=0;const ceOld=faoChainReplay;faoChainReplay=function(){ceBd++;return 0;};",
    "buildDone();",
    "faoChainReplay=ceOld;",
    "att(ceBd===1,'buildDone : branche faoChainReplay');",
    // (i) alerte fiche (stale) en mode selection de la fiche
    "const pcSt=document.createElement('div');faoSetupFiche(pcSt,faoSetup());",
    "const ceHasTxt=function(n,t){if(n.textContent&&n.textContent.indexOf(t)>=0)return true;const c=n.children||[];for(let i=0;i<c.length;i++)if(ceHasTxt(c[i],t))return true;return false;};",
    "att(ceHasTxt(pcSt,'re-s\\u00e9lectionnez la cha\\u00eene'),'fiche : alerte stale « re-s\\u00e9lectionnez la cha\\u00eene »');",
    // (i2) fiche : alerte 3+2 quand la machine est Fagor (3 axes)
    "const stF=faoSetup();const stFm=stF.machine, stFo=stF.orient;",
    "stF.machine='fagor8065';stF.orient={b:45,c:0};",
    "const pcFg=document.createElement('div');faoSetupFiche(pcFg,stF);",
    "att(ceHasTxt(pcFg,'machine 3 axes')&&ceHasTxt(pcFg,'IGNOR'),'fiche : alerte 3+2 sur Fagor (machine 3 axes)');",
    "stF.machine=stFm;stF.orient=stFo;",
    // (j) export : ATTENTION si une op a sa chaine obsolete
    "const jobS=faoDefaultSetup();jobS.name='TS';jobS.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobS.ops=[{id:'as',on:true,toolId:'T1',type:'facing',z:25,ae:6,limit:{mode:'chain',loop:[[0,0],[60,0],[60,40]],closed:true,nEdges:3,tangent:false,side:'center',extra:0,stale:true}}];",
    "const ceh=faoPost(jobS,'siemens630');",
    "att(ceh.warns.length===1&&/cha\\u00eene/.test(ceh.warns[0])&&/ATTENTION/.test(ceh.code),'export : alerte limite chaine obsolete en tete de programme');",
    "delete ceOp.limit;",
    // --- P1-b : UI pilotée dans appvm (œil, ↑/↓, +op, export)
    "doc.fao={setups:[Object.assign(faoDefaultSetup(),{name:'UITEST',stock:{x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},ops:[{id:'u1',on:true,toolId:'T1',type:'facing',z:25,ae:6},{id:'u2',on:true,toolId:'T1',type:'drill',pts:[[20,20]],ztop:25,zbot:5}]})],activeSetupId:null};",
    "sel={kind:null,id:null};document.getElementById('faoTree').children.length=0;faoRenderTree();",
    "const tr=document.getElementById('faoTree');",
    "att(tr.children.length===3,'UI oeil : arbre = posage + 2 ops');",
    "tr.children[1].children[0].onclick({stopPropagation(){}});",
    "att(faoSetup().ops[0].on===false,'UI oeil : 1er clic = operation desactivee');",
    "att(faoStatsText().indexOf('1 op')===0,'UI oeil : stats a 1 op ('+faoStatsText().slice(0,20)+')');",
    "tr.children[1].children[0].onclick({stopPropagation(){}});",
    "att(faoSetup().ops[0].on===true,'UI oeil : 2e clic = reactivee');",
    "const uS=faoSetup();",
    "const cardF=faoOpCardElement(uS,uS.ops[0],0);",
    "const dnF=cardF.children[0].children[4];",
    "att(dnF&&dnF.textContent==='\\u2193','UI fiche : bouton bas');",
    "dnF.onclick();",
    "att(uS.ops[0].type==='drill','UI \\u2193 : ordre bascule');",
    "att(docUndo()===true,'UI \\u2193 : annulable (snapshot avant mutation)');",
    "att(faoSetup().ops[0].type==='facing','UI \\u2193 : ordre restaure apres annulation');",
    "const cUp1=faoOpCardElement(faoSetup(),faoSetup().ops[0],0);",
    "cUp1.children[0].children[3].onclick();",
    "att(faoSetup().ops[0].type==='facing','UI \\u2191 en tete : sans effet (limite)');",
    "const cUp2=faoOpCardElement(faoSetup(),faoSetup().ops[1],1);",
    "cUp2.children[0].children[3].onclick();",
    "att(faoSetup().ops[0].type==='drill','UI \\u2191 : per\\u00e7age remonte en tete');",
    "const pc=document.createElement('div');faoSetupFiche(pc,faoSetup());",
    "let addRow=null;pc.children.forEach(function(c){if(c.children&&c.children.length&&String(c.children[0].textContent||'').indexOf('+')===0)addRow=c;});",
    "att(!!addRow&&addRow.children.length>=7,'UI fiche : rang des 7 boutons +op');",
    "const nB=faoSetup().ops.length;",
    "addRow.children[3].onclick();",
    "att(faoSetup().ops.length===nB+1,'UI +op : operation ajoutee');",
    "att(faoSetup().ops[nB].type==='drill','UI +op : type choisi (+ Per\\u00e7age)');",
    "globalThis.Blob=class{constructor(p){this.parts=Array.isArray(p)?p:[];this.type='';}};",
    "globalThis.__exp='';",
    "globalThis.URL={createObjectURL:function(b){globalThis.__exp=(b&&b.parts||[]).join('');return 'blob:ui';},revokeObjectURL:function(){}};",
    "const __cr=document.createElement;let __dl='';document.createElement=function(t){const n=__cr(t);if(String(t).toLowerCase()==='a'){n.click=function(){__dl=n.download;};}return n;};",
    "let expB=null;pc.children.forEach(function(c){if(c.children)c.children.forEach(function(k){if(k.textContent==='Exporter G-code')expB=k;});});",
    "att(!!expB,'UI fiche : bouton Exporter G-code');",
    "expB.onclick();",
    "att(globalThis.__exp.length>100,'UI export : G-code produit ('+globalThis.__exp.length+' car.)');",
    "att(/M30/.test(globalThis.__exp),'UI export : pied M30');",
    "att(/CYCLE81/.test(globalThis.__exp),'UI export : per\\u00e7age en cycle dialecte');",
    "att(/UITEST\\.mpf$/.test(__dl),'UI export : nom fichier ('+__dl+')');",
    "document.createElement=__cr;",
    "if(ATT.length){p('');p('ECHECS ('+ATT.length+') :');ATT.forEach(m=>p('  x '+m));}",
    "else p('TOUT EST CONFORME');",
    "p('facing='+f.length+' pocket='+pk.length+' contour='+ct.length+' drill='+dr.length);",
    "p('G1 siemens='+(s630.code.match(/\\nG1 /g)||[]).length+' G1 fagor='+(fg.code.match(/ G1 /g)||[]).length);",
    "return P.join(String.fromCharCode(10));"
  ].join('\n');
  const r=await vm.runInContext('(async()=>{'+R+'})()',ctx,{filename:'fao.js'});
  console.log(r);
  process.exit(/ECHECS|  x /.test(r)?1:0);
})().catch(e=>{console.error('ECHEC',String((e&&e.message)||e).slice(0,500));process.exit(1);});
