// FAO 3D : ébauche par tranches + finition iso-géodésique.
// Maillages synthétiques (boîte 10³, sphère lat-long) : slice, scanline,
// normales, Dijkstra, iso-courbes et génération rough3d/geofinish.
const {loadApp}=require('./appvm.cjs');
const vm=require('vm');
(async()=>{
  const {ctx}=loadApp();
  const R=[
    "const P=[];const p=s=>P.push(String(s));",
    "const ATT=[];const att=(ok,msg)=>{if(!ok)ATT.push(msg);};",
    // --- boîte 10^3, faces orientées vers l'extérieur
    "const box={v:[[0,0,0],[10,0,0],[10,10,0],[0,10,0],[0,0,10],[10,0,10],[10,10,10],[0,10,10]],",
    " t:[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[2,3,7],[2,7,6],[0,4,7],[0,7,3],[1,2,6],[1,6,5]]};",
    // --- slice à mi-hauteur : 8 segments (2 par face latérale)
    "const ss=faoSliceZ(box,5);",
    "att(ss.length===8,'slice boîte z=5 : 8 segs, vu '+ss.length);",
    "att(ss.every(s=>s.every(c=>c>=-1e-9&&c<=10+1e-9)),'slice : coords dans [0,10]');",
    // --- scanline : intervalle plein
    "const iv=faoScanIntervals(ss,5);",
    "att(iv.length===1&&Math.abs(iv[0][0])<1e-9&&Math.abs(iv[0][1]-10)<1e-9,'scan y=5 : [0,10], vu '+JSON.stringify(iv));",
    // --- normales : sommet 6 -> (1,1,1)/v3
    "const bn=faoMeshNormals(box);",
    "const d6=(bn[6][0]+bn[6][1]+bn[6][2])/Math.sqrt(3);",
    "att(d6>0.95,'normale sommet 6 sortante : '+d6.toFixed(3));",
    // --- spot hélice : départ 2 mm au-dessus de la matière (boîte z 0..10)
    "att(faoHelixSpot(box,5,5,3,2,4,20)===12,'spot : dessus brut 10 + 2');",
    "att(faoHelixSpot(box,50,50,3,2,4,20)===6,'spot : colonne vide -> niveau + 2');",
    // --- disque : dedans/interdit, dehors autorisé
    "const bsegs=faoSliceZ(box,5);",
    "att(faoDiscClear(bsegs,5,5,2,2)===false,'disque : au centre -> interdit');",
    "att(faoDiscClear(bsegs,20,5,2,2)===true,'disque : dehors -> autorisé');",
    "att(faoDiscClear(bsegs,11.5,5,2,2)===false,'disque : à 1.5 du mur (< r=2) -> interdit');",
    // --- canal : 2 plots, la poche centrale se vide (brut-moins-pièce, D10 r=5)
    "const mkBox=function(x0,x1,y0,y1,z0,z1){return {v:[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]],t:[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[2,3,7],[2,7,6],[0,4,7],[0,7,3],[1,2,6],[1,6,5]]};};",
    "const merge=function(A,B){const off=A.v.length;return {v:A.v.concat(B.v),t:A.t.concat(B.t.map(function(t){return [t[0]+off,t[1]+off,t[2]+off];}))};};",
    "const CN=merge(mkBox(0,20,0,60,0,40),mkBox(80,100,0,60,0,40));",
    "const BX={x0:-5,y0:-5,x1:105,y1:65};",
    "const blkD=function(px,py,x0,x1,y0,y1){const dx=Math.max(x0-px,0,px-x1),dy=Math.max(y0-py,0,py-y1);return Math.hypot(dx,dy);};",
    "const rm=faoGenRough3D(CN,BX,40,0,{ap:10,ae:6,toolD:10,radial:0,axial:0,secu:45});",
    "att(rm.length>10,'canal : '+rm.length+' moves');",
    "att(rm[0].r===1,'canal : 1er move rapide');",
    // Retour 6/10 : les abouts sont à la DISTANCE PERPENDICULAIRE (r·cosθ et
    // recul y±aeA supprimés) — la zone alignée X/Y ne reflétait plus la vérité
    // physique près des coins. Vérité : disque ≥ r sur toute la pièce +
    // garde-fou course dans la boîte élargie.
    "att(rm.filter(m=>!m.r).every(m=>blkD(m.x,m.y,0,20,0,60)>=4.99&&blkD(m.x,m.y,80,100,0,60)>=4.99&&m.x>=-30&&m.x<=140&&m.y>=-30&&m.y<=100),'canal : clearance outil >= r sur les deux plots (marge comprise)');",
    "att(rm.filter(m=>m.r).every(m=>m.z>=0-1e-9),'canal : rapides jamais sous le niveau');",
    "att(rm.some(m=>!m.r&&m.x<=-5+1e-9),'canal : marge laterale degagee');",
    "att(rm.some(m=>!m.r&&m.y<=-5+1e-9),'canal : marge avant degagee');",
    "const zc={};rm.filter(m=>!m.r).forEach(m=>{zc[Math.round(m.z)]=1;});",
    "att(zc[0]&&zc[10]&&zc[20]&&zc[30],'canal : niveaux 0,10,20,30 usinés');",
    // --- hélice unitaire : rayon constant, descente monotone, retour au départ
    "const hx=faoHelixEntry(0,0,10,0,3,10);",
    "att(hx[0].r===1&&Math.abs(hx[0].x-3)<1e-9&&hx[0].z===10,'helice : depart rapide (3,0,10)');",
    "const hxc=hx.filter(m=>!m.r);",
    "att(hxc.length>10&&hxc[hxc.length-1].z===0,'helice : fond Z=0 atteint');",
    "att(hxc.every((m,i)=>i===0||m.z<=hxc[i-1].z+1e-9),'helice : descente monotone');",
    "att(hxc.every(m=>Math.abs(Math.hypot(m.x,m.y)-3)<1e-6),'helice : rayon 3 constant');",
    // --- auto -> rampe sur intervalle étroit (canal D10 : on force étroit)
    "const rn=faoGenRough3D(CN,BX,40,30,{ap:10,ae:6,toolD:10,radial:0,axial:0,secu:45,entry:'ramp'});",
    "att(rn[1].r===0&&Math.abs(rn[1].z-30)<1e-9,'rampe : 2e move au niveau 30');",
    // --- hélice forcée sur large (canal 50 >= 25)
    "const rh=faoGenRough3D(CN,BX,40,30,{ap:10,ae:6,toolD:10,radial:0,axial:0,secu:45,entry:'helix'});",
    "att(rh[1].r===0&&rh[1].z<45&&rh[1].z>30,'helice forcee : 2e move en descente');",
    "att(rh.some(m=>!m.r&&Math.abs(m.z-30)<1e-9),'helice forcee : niveau 30 atteint');",
    // --- parois pièce : x=25 et x=75 suivis sur plusieurs lignes (grille aeA=2.5)
    "att(rm.some(m=>!m.r&&Math.abs(m.x-25)<1e-9&&Math.abs(m.y-0)<1e-9),'paroi : (25,0)');",
    "att(rm.some(m=>!m.r&&Math.abs(m.x-25)<1e-9&&Math.abs(m.y-52.5)<1e-9),'paroi : (25,52.5) suivie');",
    "att(rm.some(m=>!m.r&&Math.abs(m.x-75)<1e-9),'paroi droite x=75');",
    // --- plats : au-dessus de la pièce (z=30 vide) = surfaçage pleine largeur
    "const rf=faoGenRough3D(mkBox(40,60,20,40,0,10),BX,30,10,{ap:10,ae:6,toolD:10,radial:0,axial:0,secu:35});",
    "const z20=rf.filter(m=>!m.r&&Math.abs(m.z-20)<1e-9);",
    "att(z20.some(m=>m.x<10)&&z20.some(m=>m.x>90),'plat z=20 : pleine largeur');",
    "att(rf.filter(m=>!m.r&&Math.abs(m.z-10)<1e-9).every(m=>blkD(m.x,m.y,40,60,20,40)>=4.99),'z=10 : clearance >= r sur la piece (emprise respectee)');",
    "att(rf.filter(m=>!m.r&&Math.abs(m.z-10)<1e-9).some(m=>m.x<0),'plat z=10 : marge laterale degagee');",
    // --- marches : plots larges en bas, étroits en haut (raffinement auto)
    "const ST=merge(merge(mkBox(0,30,0,60,0,20),mkBox(70,100,0,60,0,20)),merge(mkBox(0,20,0,60,20,40),mkBox(80,100,0,60,20,40)));",
    "const mo=faoGenRough3D(ST,BX,40,0,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45});",
    "const z30=mo.filter(m=>!m.r&&Math.abs(m.z-30)<1e-9);",
    "att(z30.some(m=>m.x>23&&m.x<27),'troco : paroi gauche ~25.5');",
    "att(z30.some(m=>m.x>44&&m.x<46),'troco : passage interieur ~45');",
    "const consec=function(arr){const out=[];for(let i=1;i<arr.length;i++)out.push([arr[i-1],arr[i]]);return out;};",
    "att(consec(z30).some(p=>!p[0].r&&!p[1].r&&Math.abs(p[0].x-p[1].x)<0.01&&Math.abs(p[0].y-p[1].y)>2&&Math.abs(p[0].x-50)>20),'troco : flanc vertical (liaison entre lignes)');",
    // --- mode unique : les passes fines ap2 n'existent plus (pelage trocoïdal)
    "const mr=faoGenRough3D(ST,BX,40,0,{ap:10,ap2:2,ae:6,toolD:10,radial:0.5,axial:0,secu:45,entry:'ramp'});",
    "const zr={};mr.filter(m=>!m.r).forEach(m=>{zr[Math.round(m.z)]=1;});",
    "att(!zr[26],'troco : ap2 ignore, aucun niveau fin à 26');",
    "att(!zr[24],'troco : ap2 ignore, aucun niveau fin à 24');",
    // --- mode unique : l'option strategy est rejetée (sortie identique)
    "const mz=faoGenRough3D(ST,BX,40,30,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'zigzag'});",
    "const mz0=faoGenRough3D(ST,BX,40,30,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45});",
    "att(JSON.stringify(mz)===JSON.stringify(mz0),'strategy zigzag rejetee : sortie identique');",
    // --- régions : 2 colonnes disjointes sur 2 lignes = 2 régions
    "const RG=faoRoughRegions([{y:0,ivs:[{a:0,b:4},{a:6,b:10}]},{y:1,ivs:[{a:0,b:4},{a:6,b:10}]}]);",
    "att(RG.length===2&&RG.every(g=>g.length===2),'régions : 2 colonnes');",
    "att(RG.some(g=>g.every(q=>q.iv.b<=4+1e-9)),'région gauche : que [0,4]');",
    // --- mode unique : les anciennes stratégies ont été supprimées du code
    "att(typeof faoRoughLevel==='undefined'&&typeof faoRoughMorph==='undefined'&&typeof faoRoughZigzag==='undefined'&&typeof faoRoughIntervals==='undefined','mode unique : helpers morph/zigzag supprimes');",
    // --- arrondi de l'ébauche : des arcs, bornes + surépaisseur tenues
    "const mro=faoGenRough3D(ST,BX,40,30,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45});",
    "const mrr=faoRoundMoves(mro,2);",
    "att(mrr.some(m=>!m.r&&m.arc),'arrondi : arcs présents');",
    "const m30=mrr.filter(m=>!m.r&&Math.abs(m.z-30)<1e-9);",
    "att(m30.filter(m=>!m.arc).every(m=>blkD(m.x,m.y,0,20,0,60)>=4.99&&blkD(m.x,m.y,80,100,0,60)>=4.99&&m.x>=-30&&m.x<=140&&m.y>=-30&&m.y<=100),'arrondi : droites clearance >= r (marge comprise)');",
    "att(m30.every(m=>blkD(m.x,m.y,0,20,0,60)>=4.59&&blkD(m.x,m.y,80,100,0,60)>=4.59&&m.x>=-30&&m.x<=140&&m.y>=-30&&m.y<=100),'arrondi : bombe <= 0.9 (sagitta 90 degres)');",
    "att(mrr.filter(m=>!m.r&&m.arc&&!m.arc.troch).every(m=>Math.hypot(m.arc.i,m.arc.j)<=2.01),'arrondi : rayon <= 2 (hors trochoides)');",
    // --- sphère lat-long R=10 (8x12), seed = pôle nord
    "const SP={v:[[0,0,10]],t:[]};",
    "{const nL=8,nC=12,Ra=10;",
    "for(let i=1;i<nL;i++){const ph=i*Math.PI/nL;",
    " for(let j=0;j<nC;j++){const th=j*2*Math.PI/nC;",
    "  SP.v.push([Ra*Math.sin(ph)*Math.cos(th),Ra*Math.sin(ph)*Math.sin(th),Ra*Math.cos(ph)]);}}",
    "const SUD=SP.v.length;SP.v.push([0,0,-10]);",
    "const RG=function(i,j){return 1+(i-1)*nC+(((j%nC)+nC)%nC);};",
    "for(let j=0;j<nC;j++)SP.t.push([0,RG(1,j),RG(1,j+1)]);",
    "for(let i=1;i<nL-1;i++)for(let j=0;j<nC;j++)SP.t.push([RG(i,j),RG(i+1,j),RG(i+1,j+1)],[RG(i,j),RG(i+1,j+1),RG(i,j+1)]);",
    "for(let j=0;j<nC;j++)SP.t.push([SUD,RG(nL-1,j+1),RG(nL-1,j)]);}",
    "att(SP.t.length===12+6*12*2+12,'sphere : 168 tris, vu '+SP.t.length);",
    "const sn=faoMeshNormals(SP);",
    "let out=0;for(let i=0;i<SP.v.length;i++){const l=Math.hypot(SP.v[i][0],SP.v[i][1],SP.v[i][2])||1;",
    " if((SP.v[i][0]*sn[i][0]+SP.v[i][1]*sn[i][1]+SP.v[i][2]*sn[i][2])/l<0.9)out++;}",
    "att(out===0,'sphere : normales sortantes ('+out+' KO)');",
    "const sd=faoDijkstra(SP,faoSeedTop(SP));",
    "let dm=0;for(let i=0;i<sd.length;i++)if(sd[i]<1/0&&sd[i]>dm)dm=sd[i];",
    "p('dmax sphere R10 : '+dm.toFixed(2)+' (attendu ~31.4)');",
    "att(dm>25&&dm<33,'dmax dans [25,33]');",
    // --- finition géodésique : anneaux au pas 5, centres à R+4
    "const gm=faoGenGeoFinish(SP,{step:5,toolD:8,kind:'ball',laisse:0,secu:30,seed:'top'});",
    "att(gm.length>20,'geofinish : '+gm.length+' moves');",
    "const cuts=gm.filter(m=>!m.r);",
    "const rr=cuts.map(m=>Math.hypot(m.x,m.y,m.z));",
    "const rmoy=rr.reduce((a,b)=>a+b,0)/rr.length;",
    "p('rayon moyen centres : '+rmoy.toFixed(2)+' (attendu ~14)');",
    "att(rmoy>13&&rmoy<15,'centres outil à R+4');",
    "att(cuts[0].z>5,'1er anneau près du sommet : z='+cuts[0].z.toFixed(1));",
    // --- hélice d'entrée sur sphère (équateur large, SP défini plus haut)
    "const mh=faoGenRough3D(SP,{x0:-12,y0:-12,x1:12,y1:12},20,0,{ap:10,ae:4,toolD:4,radial:0.5,axial:0,secu:30});",
    "att(mh.some(m=>!m.r&&m.z>10&&m.z<30),'sphere : descente entree 20->10');",
    // --- pelage trocoïdal : petit pas + stay-down + trochoide (canal CN, BX)
    "const ad=faoGenRough3D(CN,BX,40,30,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive'});",
    "att(ad.length>50,'adaptive : '+ad.length+' moves');",
    "att(ad[0].r===1,'adaptive : 1er move rapide');",
    "att(ad.filter(m=>!m.r).every(m=>blkD(m.x,m.y,0,20,0,60)>=5.49&&blkD(m.x,m.y,80,100,0,60)>=5.49&&m.x>=-30&&m.x<=140&&m.y>=-30&&m.y<=100),'adaptive : clearance outil >= r (marge comprise)');",
    "att(ad.some(m=>!m.r&&m.z>30&&m.z<45),'adaptive : descente helice');",
    "att(ad.filter(m=>m.r).length<=12,'adaptive : stay-down, '+ad.filter(m=>m.r).length+' rapides (1 entree par colonne)');",
    "const mo1=faoGenRough3D(CN,BX,40,30,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'morph'});",
    "att(ad.filter(m=>!m.r).length===mo1.filter(m=>!m.r).length,'strategy morph rejetee : meme sortie troco');",
    // --- adaptive en goulet 15 mm (D10) : trochoides, pas de droite pleine largeur
    "const NB=merge(mkBox(0,42.5,0,60,0,40),mkBox(57.5,100,0,60,0,40));",
    "const az=faoGenRough3D(NB,BX,40,30,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive'});",
    "att(az.length>20,'adaptive goulet : '+az.length+' moves');",
    "att((function(){const s={};az.filter(m=>!m.r).forEach(m=>{s[Math.round(m.y*10)/10]=1;});return Object.keys(s).length;})()>24,'adaptive goulet : oscillation Y (trochoide)');",
    "att(az.some(m=>!m.r&&m.arc),'adaptive goulet : arcs G2/G3 presents');",
    "att(az.filter(m=>!m.r&&m.arc).every(m=>{const q=Math.hypot(m.arc.i,m.arc.j);return q>=0.4&&q<=3.1;}),'adaptive goulet : rayons trochoides coherents');",
    "att(az.filter(m=>!m.r&&m.arc).every(m=>!m.arc.cw),'adaptive goulet : trochoides CCW (G3)');",
    // --- adaptive : ombre du brut restant (queue d'aronde : large en haut)
    "const DV=merge(mkBox(40,60,0,60,0,20),mkBox(30,70,0,60,20,40));",
    "const BX2={x0:0,y0:-5,x1:100,y1:65};",
    "const av=faoGenRough3D(DV,BX2,40,0,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive'});",
    "const c10=av.filter(m=>!m.r&&Math.abs(m.z-10)<1e-9);",
    "att(c10.length>0,'adaptive surplomb : niveau bas usine');",
    "att(c10.every(m=>blkD(m.x,m.y,30,70,0,60)>=5.49),'adaptive surplomb : jamais sous le porte-a-faux [30,70]');",
    "att(av.some(m=>!m.r&&Math.abs(m.z-30)<1e-9),'adaptive surplomb : niveau haut usine');",
    // --- adaptive : micro-entree en fente ~D (12 mm, D10 : ni helice ni rampe)",
    "const NS=merge(mkBox(0,44,0,60,0,40),mkBox(56,100,0,60,0,40));",
    "const an=faoGenRough3D(NS,BX,40,30,{ap:10,ae:6,toolD:10,radial:0,axial:0,secu:45,strategy:'adaptive'});",
    "att(an.length>10&&an[0].r===1,'adaptive fente : '+an.length+' moves, demarre rapide');",
    "att(an.filter(m=>!m.r).every(m=>blkD(m.x,m.y,0,44,0,60)>=4.98&&blkD(m.x,m.y,56,100,0,60)>=4.98),'adaptive fente : clearance outil >= r sur les deux plots');",
    // --- trochoide : excursion Y bornee a la bande balayee + repli droit
    "const tc=[];faoTrochSlot(tc,0,20,5,10,10,2.5,5,5);",
    "att(tc.some(m=>!m.r&&m.arc),'troch clamp : arcs si place reduite en Y');",
    "att(tc.filter(m=>!m.r).every(m=>Math.abs(m.y-5)<=1.26),'troch clamp : |dY| <= bord (1.25)');",
    "const ts=[];faoTrochSlot(ts,0,20,5,10,10,0.5,5,5);",
    "att(ts.length>0&&ts.every(m=>!m.arc),'troch repli : droit si pas de place');",
    "att(ts.filter(m=>!m.r).every(m=>m.x>=-1e-9&&m.x<=20+1e-9&&Math.abs(m.y-5)<1e-9),'troch repli : reste sur la ligne');",
    // --- ombre exacte : voile fin 24.3-24.9 (hors grille 2 mm) jamais traverse
    "const VL=merge(mkBox(40,60,0,60,0,10),mkBox(30,70,0,60,24.3,24.9));",
    "const vv=faoGenRough3D(VL,BX2,40,0,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive'});",
    "const c20=vv.filter(m=>!m.r&&Math.abs(m.z-20)<1e-9);",
    "att(c20.length>0,'adaptive voile : niveau 20 usine autour');",
    "att(c20.every(m=>blkD(m.x,m.y,30,70,0,60)>=5.49),'adaptive voile : voile fin jamais traverse');",
    "att(Math.abs(faoHelixSpot(VL,50,30,3,5.5,20,40,[0,10,24.3,24.9])-26.9)<1e-9,'helice plans : depart au-dessus du voile');",
    // --- sens long : brut PORTRAIT -> pelage le long de Y (liaisons longues verticales)
    "const BP={x0:0,y0:0,x1:60,y1:120};",
    "const mp=faoGenRough3D(mkBox(10,50,10,110,0,20),BP,30,0,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive'});",
    "let lv=0,pp=null;mp.forEach(function(m){if(m.r){pp=null;return;}if(pp&&Math.abs(m.x-pp.x)<1e-6&&Math.abs(m.y-pp.y)>5)lv++;pp=m;});",
    "att(lv>0,'sens long : liaison longue verticale sur brut portrait ('+lv+')');",
    // --- mini-passes Z : contours de parois entre plans trocoïdaux (retour 4/10)
    // Plaque 60x40x18, ap=6 -> plans [12,6,0] ; bandes de 6 mm ; minipasses=2
    // -> z = 16,14 / 10,8 / 4,2 (k*ap/(nb+1) sous le plan du dessus, strictement
    // entre les plans). Offsets s = radial*(nb-k)/nb -> 0.25 puis 0 au plus profond.
    "const PL=mkBox(20,80,20,60,0,18);",
    "const mm=faoGenRough3D(PL,BX,18,0,{ap:6,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive',minipasses:2});",
    "const mid=function(ms,rr){return ms.filter(m=>blkD(m.x,m.y,20,80,20,60)<rr-0.01).length;};",
    "const m16=mm.filter(m=>!m.r&&Math.abs(m.z-16)<1e-6),m14=mm.filter(m=>!m.r&&Math.abs(m.z-14)<1e-6);",
    "att(m16.length>5&&m14.length>5,'mini passes : plans z=16/14 usines ('+m16.length+'/'+m14.length+' moves)');",
    "att(mid(m16,5.25)<=4,'mini passe 1 (z=16, s=0.25) : contour de parois seul ('+mid(m16,5.25)+' moves sous r_eff)');",
    "att(mid(m14,5)<=4,'mini passe 2 (z=14, s=0) : contour de parois seul ('+mid(m14,5)+' moves sous r_eff)');",
    "att(mm.some(m=>!m.r&&Math.abs(m.z-12)<1e-6),'mini passes : plan trocoïdal z=12 toujours usine');",
    "const m0=faoGenRough3D(PL,BX,18,0,{ap:6,ae:6,toolD:10,radial:0.5,axial:0,secu:45,strategy:'adaptive'});",
    "att(m0.filter(m=>!m.r&&Math.abs(m.z-16)<1e-6).length===0,'minipasses off par defaut : aucun plan z=16');",
    // --- geodésique 6+2 : sens horizontal, limites Z, garde-fou fraise droite (retour 4/10)
    "const PLN={v:[[0,0,30],[60,0,30],[60,40,30],[0,40,30]],t:[[0,1,2],[0,2,3]]};",
    "const SL={v:[[0,0,0],[40,0,20],[40,20,20],[40,40,20],[0,40,0]],t:[[0,1,2],[0,2,3],[0,3,4]]};",
    // formes : offsets outil sur plan horizontal (ball D8 +4, bull coin1 +1, droite +0)
    "const gB=faoGenGeoFinish(PLN,{step:6,toolD:8,kind:'ball',laisse:0,secu:45,seed:'top'});",
    "const zB=gB.filter(m=>!m.r).map(m=>m.z);",
    "att(zB.length>4&&Math.abs(Math.max.apply(null,zB)-34)<1e-6,'geo formes : ball D8 sur plan z=30 -> coupe z=34, vu '+(zB.length?Math.max.apply(null,zB):'-'));",
    "const gU=faoGenGeoFinish(PLN,{step:6,toolD:8,kind:'bull',cornerR:1,laisse:0,secu:45,seed:'top'});",
    "const zU=gU.filter(m=>!m.r).map(m=>m.z);",
    "att(zU.length>4&&Math.abs(Math.max.apply(null,zU)-31)<1e-6,'geo formes : bull coin1 sur plan -> coupe z=31, vu '+(zU.length?Math.max.apply(null,zU):'-'));",
    "const gF=faoGenGeoFinish(PLN,{step:6,toolD:8,kind:'flat',laisse:0,secu:45,seed:'top'});",
    "const zF=gF.filter(m=>!m.r).map(m=>m.z);",
    "att(zF.length>4&&Math.abs(Math.max.apply(null,zF)-30)<1e-6,'geo formes : fraise droite sur plan -> coupe z=30, vu '+(zF.length?Math.max.apply(null,zF):'-'));",
    // sens horizontal : passes iso-Z sur la rampe (chaque liaison reste a Z constant)
    "const gS=faoGenGeoFinish(SL,{step:5,toolD:8,kind:'ball',laisse:0,secu:45,seed:'top'});",
    "const cs=gS.filter(m=>!m.r);",
    "att(cs.length>6,'geo rampe : '+cs.length+' coupe outil');",
    "let badZ=0,run=[];gS.forEach(function(m){if(!m.r){run.push(m.z);return;}if(run.length>1){const z0=run[0];if(run.some(function(z){return Math.abs(z-z0)>1e-6;}))badZ++;}run=[];});",
    "att(badZ===0,'geo sens horizontal : chaque liaison a Z constant ('+badZ+' liaisons variables)');",
    // limites Z : ztop=12 -> aucune coupe au-dessus de 12+Rc
    "const gL=faoGenGeoFinish(SL,{step:5,toolD:8,kind:'ball',laisse:0,secu:45,seed:'top',ztop:12});",
    "const zL=gL.filter(m=>!m.r).map(m=>m.z);",
    "att(zL.length>0&&Math.max.apply(null,zL)<16,'geo limites Z : ztop=12 -> coupe max '+(zL.length?Math.max.apply(null,zL).toFixed(2):'-')+' < 16');",
    // garde-fou fraise droite : refusee sur non-horizontal, acceptee sur plan
    "att(faoGenGeoFinish(SL,{step:5,toolD:8,kind:'flat',laisse:0,secu:45}).length===0,'geo garde-fou : fraise droite refusee sur rampe');",
    "att(faoGenGeoFinish(PLN,{step:6,toolD:8,kind:'flat',laisse:0,secu:45}).length>0,'geo garde-fou : fraise droite acceptee sur plan');",
    // --- dispatch via ops (maillage actif nul en VM -> [] sans planter)
    "const j3=faoDefaultJob();j3.ops=[{id:'x',on:true,toolId:'T3',type:'geofinish',step:1,laisse:0,seed:'top'}];",
    "att(Array.isArray(faoOpMoves(j3.ops[0],j3)),'dispatch geofinish sans maillage : pas de plantage');",
    // --- 025 : ébauche 3D — lignes bornées au RAYON sur les murs en Y (retour 4/10 pt 2)
    // Boîte 100x80x50, poche x10..90 y19..63 z20..50 ouverte dessus, D16 r=8 ae=4 :
    // les lignes de pelage doivent rester à >= r des parois Y (l'existence lisait
    // y±aeA (6<r) et laissait passer jusqu'à mur∓aeA -> gradins). X exact (r déjà
    // appliqué), marge pleine largeur (d>=r, tangence) intacte.
    "const cavM=(function(){",
    "  const V=[],T=[];",
    "  const Q=function(a,b,c,d){T.push([V.length,V.length+1,V.length+2]);T.push([V.length,V.length+2,V.length+3]);V.push(a,b,c,d);};",
    "  Q([0,0,0],[100,0,0],[100,80,0],[0,80,0]);",
    "  Q([0,0,0],[0,80,0],[0,80,50],[0,0,50]);",
    "  Q([100,0,0],[100,80,0],[100,80,50],[100,0,50]);",
    "  Q([0,0,0],[100,0,0],[100,0,50],[0,0,50]);",
    "  Q([0,80,0],[100,80,0],[100,80,50],[0,80,50]);",
    "  Q([10,19,20],[90,19,20],[90,63,20],[10,63,20]);",
    "  Q([10,19,20],[10,63,20],[10,63,50],[10,19,50]);",
    "  Q([90,19,20],[90,63,20],[90,63,50],[90,19,50]);",
    "  Q([10,19,20],[90,19,20],[90,19,50],[10,19,50]);",
    "  Q([10,63,20],[90,63,20],[90,63,50],[10,63,50]);",
    "  Q([0,0,50],[10,0,50],[10,80,50],[0,80,50]);",
    "  Q([90,0,50],[100,0,50],[100,80,50],[90,80,50]);",
    "  Q([10,0,50],[90,0,50],[90,19,50],[10,19,50]);",
    "  Q([10,63,50],[90,63,50],[90,80,50],[10,80,50]);",
    "  return {v:V,t:T};",
    "})();",
    "const cB={x0:-6,y0:-6,z0:0,x1:106,y1:86,z1:50};",
    "const cm=faoGenRough3D(cavM,cB,45,25,{ap:5,ae:4,toolD:16,radial:0,axial:0,secu:60,brutTop:50});",
    "const c30=cm.filter(m=>!m.r&&Math.abs(m.z-30)<1e-9);",
    "att(c30.length>20,'025 poche : niveau z=30 usine ('+c30.length+' moves)');",
    "const cY=c30.filter(m=>m.y>19&&m.y<63&&m.x>18&&m.x<82);",
    "att(cY.length>4,'025 poche : '+cY.length+' coupe dans la poche');",
    "const pYmax=Math.max.apply(null,cY.map(m=>m.y));",
    "const pYmin=Math.min.apply(null,cY.map(m=>m.y));",
    "att(pYmax<=63-8+0.6,'025 mur Y haut : bordé au rayon (y max '+pYmax.toFixed(2)+' <= 55.6)');",
    "att(pYmin>=19+8-0.6,'025 mur Y bas : bordé au rayon (y min '+pYmin.toFixed(2)+' >= 26.4)');",
    "const cX=c30.filter(m=>Math.abs(m.y-38)<1e-9&&m.x>=18&&m.x<=82);",
    "const xm=cX.length?Math.max.apply(null,cX.map(m=>m.x)):NaN;",
    "att(isFinite(xm)&&xm>=82-0.6&&xm<=82+0.6,'025 mur X : exact au rayon (x max '+xm.toFixed(2)+' ~ 82)');",
    "att(c30.some(m=>m.y===-10&&m.x<=-14+1e-6),'025 marge : ligne pleine largeur conservee (y=-10, x<=-14)');",
    // --- 027 : suivi de contour — pas de barrage d'excroissance, collé à 0,5.
    // Plaque + tenon (excroissance vers la marge) : l'ancien scanline abandonnait
    // la ligne y=4.5 (bande morte 2→7 traversant toute la marge = barrage).
    // (a) couverture : tout échantillon libre (dist >= r) à <= 1,9 mm d'une
    //     coupe (pas de bande > ~2 mm) ; (b) point de l'ancienne bande usiné ;
    // (c) aucune coupe < 5,49 (gouge) ; (d) au moins une coupe à 5,5 (collé).
    "const QP=merge(mkBox(20,80,20,60,0,20),mkBox(45,55,8,20,0,30));",
    "const QB={x0:0,y0:0,x1:100,y1:80};",
    "const qm=faoGenRough3D(QP,QB,30,0,{ap:10,ae:6,toolD:10,radial:0.5,axial:0,secu:45});",
    "const qD=function(px,py){return Math.min(blkD(px,py,20,80,20,60),blkD(px,py,45,55,8,20));};",
    "const qPS=function(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],L2=dx*dx+dy*dy;let t=L2>0?((p[0]-a[0])*dx+(p[1]-a[1])*dy)/L2:0;t=t<0?0:t>1?1:t;return Math.hypot(p[0]-(a[0]+dx*t),p[1]-(a[1]+dy*t));};",
    "const qCuts=[];",
    "{let last=null;qm.forEach(function(m){",
    "  if(m.r||Math.abs(m.z-10)>1e-6){last=null;return;}",
    "  if(last)qCuts.push([last,[m.x,m.y]]);",
    "  last=[m.x,m.y];",
    "});}",
    "att(qCuts.length>50,'027 : '+qCuts.length+' segments de coupe au niveau z=10');",
    "let qW=0,qWp=null,qN=0;",
    "for(let px=-5;px<=105;px++)for(let py=-5;py<=85;py++){",
    "  if(qD(px,py)<5.499)continue;",
    "  qN++;",
    "  const p=[px,py];let best=1/0;",
    "  for(let i=0;i<qCuts.length;i++){const d=qPS(p,qCuts[i][0],qCuts[i][1]);if(d<best)best=d;}",
    "  if(best>qW){qW=best;qWp=[px,py];}",
    "}",
    "att(qN>800,'027 : '+qN+' échantillons libres');",
    "att(qW<=1.9,'027 couverture : écart max '+qW.toFixed(2)+' mm en ('+(qWp?qWp[0]+','+qWp[1]:'?')+'), suivi de contour sans bande morte (<=1,9)');",
    "let qBd=1/0;",
    "qCuts.forEach(function(sg){qBd=Math.min(qBd,qPS([40,4.5],sg[0],sg[1]));});",
    "att(qBd<=1.9,'027 barrage : coupe à '+qBd.toFixed(2)+' mm de (40,4.5), ancienne bande 2→7 usinée (<=1,9)');",
    "let qMin=1/0;",
    "qCuts.forEach(function(sg){[sg[0],sg[1]].forEach(function(p){const d=qD(p[0],p[1]);if(d<qMin)qMin=d;});});",
    "att(qMin>=5.49,'027 gouge : coupe la plus proche '+qMin.toFixed(3)+' mm de la matière (>=5,49)');",
    "att(qMin<=5.51,'027 collé : '+qMin.toFixed(3)+' mm <= 5,51 (section suivie à 0,5)');",
    // --- 2026-10-04-009 : entrées géofinition — mode, garde hélice, groupement par zone
    "att(typeof faoGeoEntryMode==='function','geo entree : faoGeoEntryMode definie');",
    "if(typeof faoGeoEntryMode==='function'){",
    "  att(faoGeoEntryMode('ramp',true)==='ramp','geo entree : ramp forcee');",
    "  att(faoGeoEntryMode('helix',true)==='helix','geo entree : helix si ebauche avant');",
    "  att(faoGeoEntryMode('helix',false)==='ramp','geo entree : helice INTERDITE sans ebauche avant');",
    "  att(faoGeoEntryMode('auto',false)==='ramp','geo entree : auto sans ebauche -> ramp');",
    "  att(faoGeoEntryMode('auto',true)==='auto','geo entree : auto avec ebauche');",
    "  att(faoGeoEntryMode(undefined,false)==='ramp','geo entree : defaut sans ebauche -> ramp');",
    "  att(faoGeoEntryMode(undefined,true)==='auto','geo entree : defaut avec ebauche -> auto');",
    "  att(faoGeoEntryMode('bidon',false)==='ramp','geo entree : valeur inconnue -> ramp');",
    "}",
    "att(typeof faoGeoHasRrough==='function','geo entree : faoGeoHasRrough definie');",
    "if(typeof faoGeoHasRrough==='function'){",
    "  const JR={ops:[{id:'r',type:'rough3d',on:true},{id:'g',type:'geofinish'}]};",
    "  att(faoGeoHasRrough(JR,JR.ops[1])===true,'geo entree : ebauche 3D active avant -> true');",
    "  const JO={ops:[{id:'r',type:'rough3d',on:false},{id:'g',type:'geofinish'}]};",
    "  att(faoGeoHasRrough(JO,JO.ops[1])===false,'geo entree : ebauche desactivee avant -> false');",
    "  const JD={ops:[{id:'r',type:'pocket3d',on:true},{id:'g',type:'geofinish'}]};",
    "  att(faoGeoHasRrough(JD,JD.ops[1])===false,'geo entree : pocket3d supprime -> false');",
    "  const JV={ops:[{id:'g',type:'geofinish'}]};",
    "  att(faoGeoHasRrough(JV,JV.ops[0])===false,'geo entree : aucune operation avant -> false');",
    "  att(faoGeoHasRrough({ops:[]},{id:'z',type:'geofinish'})===false,'geo entree : op introuvable -> false');",
    "}",
    "att(faoOpDefaults('geofinish').entry==='auto','geo entree : defaut entry auto');",
    // Hélice sans ébauche : identique au ramp (l'entrée est ignorée en sécurité)
    "const gXr=faoGenGeoFinish(SL,{step:5,toolD:8,kind:'ball',laisse:0,secu:45,entry:'ramp'});",
    "const gXh=faoGenGeoFinish(SL,{step:5,toolD:8,kind:'ball',laisse:0,secu:45,entry:'helix'});",
    "att(JSON.stringify(gXh)===JSON.stringify(gXr),'geo entree : helix sans ebauche = ramp (sortie identique)');",
    // 3 tours égaux : iso à chaque niveau = 3 chaînes/niveau (regroupement par zone)
    "const TW=merge(merge(mkBox(0,20,0,20,0,40),mkBox(40,60,0,20,0,40)),mkBox(80,100,0,20,0,40));",
    "const gT=faoGenGeoFinish(TW,{step:6,toolD:8,kind:'ball',laisse:0,secu:45,seed:'top',entry:'ramp'});",
    "att(gT.length>50,'geo zones : '+gT.length+' moves (3 tours)');",
    "const secOK=function(m){return m.r===1&&Math.abs(m.z-45)<1e-9;};",
    "let nS=0,nZ=0;",
    "for(let i=0;i<gT.length;i++){",
    "  if(!secOK(gT[i]))continue;",
    "  nS++;",
    "  const prevCut=i>0&&gT[i-1].r===0;",
    "  const nextSec=(i===gT.length-1)||secOK(gT[i+1]);",
    "  if(prevCut&&nextSec)nZ++;",
    "}",
    "p('geo zones : rapides a secu='+nS+' zones='+nZ);",
    "att(nZ>=6,'geo zones : au moins 6 zones (niveaux iso), vu '+nZ);",
    "att(nS<=2*nZ+2,'geo groupement : rapides a secu '+nS+' <= 2*zones+2='+(2*nZ+2));",
    // Hélice avec débourrage avant : l'entrée change vraiment (spot disjoint des tours)
    "const gXe=faoGenGeoFinish(TW,{step:6,toolD:8,kind:'ball',laisse:0,secu:45,seed:'top',entry:'helix',hasRrough:true});",
    "att(gXe.length>50&&JSON.stringify(gXe)!==JSON.stringify(gT),'geo entree : helix avec ebauche avant change l entree');",
    "if(ATT.length){p('');p('ECHECS ('+ATT.length+') :');ATT.forEach(m=>p('  x '+m));}",
    "else p('TOUT EST CONFORME');",
    "return P.join(String.fromCharCode(10));"
  ].join('\n');
  const r=await vm.runInContext('(async()=>{'+R+'})()',ctx,{filename:'fao3d.js'});
  console.log(r);
  process.exit(/ECHECS|  x /.test(r)?1:0);
})().catch(e=>{console.error('ECHEC',String((e&&e.message)||e).slice(0,500));process.exit(1);});
