// FAO : posages + parcours 2.5D + post-processeurs Siemens 840D / Fagor 8065.
// Pur logique (aucun OCCT) : modèle posage, origine G54, générateurs,
// post-pros, arbre FAO, fiches panneau droit, persistance — sans rejeu.
const {loadApp}=require('./appvm.cjs');
const vm=require('vm');
(async()=>{
  const {ctx}=loadApp();
  const R=[
    "const P=[];const p=s=>P.push(String(s));",
    "const ATT=[];const att=(ok,msg)=>{if(!ok)ATT.push(msg);};",
    // --- formats
    "att(faoFmtXYZ(10)==='10.000','fmt XYZ entier : '+faoFmtXYZ(10));",
    "att(faoFmtXYZ(12.34567)==='12.346','fmt XYZ arrondi : '+faoFmtXYZ(12.34567));",
    "att(faoFmtF(1200)==='1200.0','fmt feed : '+faoFmtF(1200));",
    "att(faoProgName('ma piece!')==='MA_PIECE_','prog name : '+faoProgName('ma piece!'));",
    // --- niveaux
    "const lv=faoLevels(25,0,10);",
    "att(JSON.stringify(lv)===JSON.stringify([15,5,0]),'niveaux 25->0 ap10 : '+JSON.stringify(lv));",
    // --- racine posages
    "const rt0=faoRoot();",
    "att(rt0.setups.length===1&&rt0.activeSetupId===rt0.setups[0].id,'root : 1 posage actif');",
    "att(faoSetup().machine==='siemens630','setup defaut : machine 630');",
    // --- job de test
    "const job=faoDefaultJob();job.name='TEST';job.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "job.ops=[{type:'facing',z:25,ae:6},{type:'pocket',x0:10,y0:10,x1:90,y1:70,ztop:25,zbot:5,ap:10,ae:5},{type:'contour',x0:10,y0:10,x1:90,y1:70,ztop:5,zbot:0,ap:5},{type:'drill',pts:[[20,20],[80,60]],ztop:25,zbot:5}];",
    // --- surfaçage
    "const f=faoOpMoves(job.ops[0],job);",
    "att(f.length>10,'facing : '+f.length+' moves');",
    "att(f[0].r===1,'facing : 1er move rapide');",
    "att(f.filter(m=>!m.r).every(m=>Math.abs(m.z-25)<1e-9),'facing : toute la coupe à Z=25');",
    "att(f.every(m=>m.y>=-5.01&&m.y<=85.01),'facing : Y dans [y0-r,y1+r]');",
    "att(f.filter(m=>m.r).every(m=>m.z>=25-1e-9),'facing : rapides au-dessus du brut (Z>=25)');",
    // --- poche
    "const pk=faoOpMoves(job.ops[1],job);",
    "att(pk.length>20,'pocket : '+pk.length+' moves');",
    "att(pk.every(m=>m.x>=9.99&&m.x<=90.01&&m.y>=9.99&&m.y<=70.01),'pocket : XY dans le rectangle');",
    "att(pk.some(m=>!m.r&&Math.abs(m.z-5)<1e-9),'pocket : fond Z=5 atteint');",
    // --- contour
    "const ct=faoOpMoves(job.ops[2],job);",
    "att(ct.length>0,'contour : moves');",
    "att(ct.some(m=>!m.r&&Math.abs(m.x-95)<1e-9),'contour : compensation +r (x1+D/2=95)');",
    "att(ct.filter(m=>!m.r).every(m=>Math.abs(m.z-0)<1e-9),'contour : 1 niveau Z=0 (5->0 ap5)');",
    // --- perçage
    "const dr=faoOpMoves(job.ops[3],job);",
    "att(dr.length===8,'drill 2 trous : 8 moves, vu '+dr.length);",
    "att(dr.filter(m=>!m.r).every(m=>Math.abs(m.z-5)<1e-9),'drill : fond Z=5');",
    // --- estimation
    "const e=faoEstimate(f,faoToolSF(job.tools[0]).f,5000);",
    "att(e.cut>0&&e.tmin>0,'estimation : cut='+e.cut.toFixed(0)+' t='+e.tmin.toFixed(2));",
    // --- post Siemens 630
    "const s630=faoPost(job,'siemens630');",
    "att(s630.ext==='mpf','siemens ext mpf');",
    "att(s630.code.indexOf('; %_N_TEST_MPF')===0,'siemens : en-tete %_N_');",
    "att(/G71/.test(s630.code)&&/G17 G90 G94 G54/.test(s630.code),'siemens : G71/G17/G90/G94/G54');",
    "att(/\\nT1 D1\\n/.test(s630.code),'siemens : appel outil T1 D1');",
    "att(/X-200/.test(s630.code),'siemens630 : parc X-200');",
    "att(/M30/.test(s630.code),'siemens : M30');",
    "att(!/^N[0-9]+ /m.test(s630.code),'siemens : pas de numeros de sequence');",
    "att((s630.code.match(/\\nG1 /g)||[]).length>20,'siemens : G1 bien presents');",
    // --- variante 1520 : seul le parc change
    "const s1520=faoPost(job,'siemens1520');",
    "att(/X-430/.test(s1520.code),'siemens1520 : parc X-430');",
    "att(s1520.code.replace(/X-430/g,'X-200').replace(/1520/g,'630')===s630.code,'1520 vs 630 : seule difference = parc X (+ nom en-tete)');",
    // --- post Fagor 8065
    "const fg=faoPost(job,'fagor8065');",
    "att(fg.ext==='nc','fagor ext nc');",
    "att(/^\\(TEST/.test(fg.code),'fagor : commentaire (NOM ...)');",
    "att(/M06/.test(fg.code)&&/M03/.test(fg.code),'fagor : M06/M03');",
    "att(/^N10 /m.test(fg.code),'fagor : sequences des N10');",
    "att(/M30/.test(fg.code),'fagor : M30');",
    "att((fg.code.match(/ G1 /g)||[]).length===(s630.code.match(/\\nG1 /g)||[]).length,'fagor/siemens : meme nombre de G1');",
    "att(fg.code.indexOf('SUPA')<0,'fagor : pas de SUPA (inconnu sur Fagor)');",
    // --- parité des avances (plongée Fagor = plongée Siemens, jamais sur un XY seul)
    "const sfp=faoFmtF(faoToolSF(job.tools[0]).plunge),fsCut=faoFmtF(faoToolSF(job.tools[0]).f);",
    "const fsS=(s630.code.match(/ F[0-9.]+/g)||[]).join(','),fsF=(fg.code.match(/ F[0-9.]+/g)||[]).join(',');",
    "att(fsS===fsF,'fagor/siemens : meme sequence d avances F ('+fsS.length+' mots)');",
    "const badPl=(fg.code.match(/\\nN[0-9]+ G1 [^\\n]*/g)||[]).filter(l=>l.indexOf(' F'+sfp)>=0&&l.indexOf('Z')<0);",
    "att(sfp===fsCut||badPl.length===0,'fagor : F plongee jamais sur un XY seul (vu '+badPl.length+')');",
    // --- P0-4 : G40/G80 en entête + garde-fou « coupe sous le brut »
    "att(/G40 G80 G17 G90 G94 G54/.test(s630.code),'siemens : G40 G80 en entete');",
    "att(/G40 G80 G17/.test(fg.code),'fagor : G40 G80 en entete');",
    "att(s630.warns&&s630.warns.length===0,'job normal : aucune alerte sous le brut');",
    "const jobZ=faoDefaultSetup();jobZ.name='ZTEST';jobZ.stock={x0:0,y0:0,z0:0,x1:50,y1:50,z1:10};",
    "jobZ.ops=[{id:'z1',on:true,toolId:'T1',type:'drill',pts:[[25,25]],ztop:10,zbot:-3}];",
    "const gz=faoPost(jobZ,'siemens630');",
    "att(gz.warns&&gz.warns.length===1,'garde-fou : 1 alerte sous le brut ('+(gz.warns||[]).join('|')+')');",
    "att(/ATTENTION/.test(gz.code)&&/sous le brut/.test(gz.code),'garde-fou : mentionnee dans le G-code');",
    "const gzF=faoPost(jobZ,'fagor8065');",
    "att(gzF.warns.length===1&&/\\( ATTENTION/.test(gzF.code),'garde-fou fagor : ( ATTENTION ... )');",
    "att(/CYCLE81/.test(gz.code),'garde-fou : per\\u00e7age alarm\\u00e9 reste en cycle');",
    // --- P1-a : cycles de per\\u00e7age dialecte (golden tests)
    "att(/CYCLE81\\(5\\.000, 0\\.000, 5\\.000, -20\\.000, \\)/.test(s630.code),'siemens : CYCLE81 (golden)');",
    "att(!/CYCLE83/.test(s630.code),'sans Q : pas de CYCLE83');",
    "att(/G0 X20\\.000 Y20\\.000 Z5\\.000 F/.test(s630.code),'siemens : trou au retrait, F plong\\u00e9e sur le G0');",
    "att(/G98 G81 X20\\.000 Y20\\.000 Z5\\.000 I-20\\.000/.test(fg.code),'fagor : G98 G81 (golden)');",
    "att(/G80/.test(fg.code),'fagor : G80 annule le cycle');",
    "att(!/G83/.test(fg.code),'sans Q : pas de G83 fagor');",
    // --- P1-a : broche \\u00e0 va-et-vient (Q / peck)
    "const jobPk=faoDefaultSetup();jobPk.name='PK';jobPk.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobPk.ops=[{id:'k1',on:true,toolId:'T1',type:'drill',pts:[[20,20],[80,60]],ztop:25,zbot:5,peck:4}];",
    "const spk=faoPost(jobPk,'siemens630').code;",
    "att(/CYCLE83\\(5\\.000, 0\\.000, 5\\.000, -20\\.000, , -4\\.000/.test(spk),'siemens : CYCLE83 Q=4 (golden, FDEP=RFP-Q)');",
    "att(!/CYCLE81\\(/.test(spk),'Q>0 : CYCLE81 remplac\\u00e9 par CYCLE83');",
    "const fpk=faoPost(jobPk,'fagor8065').code;",
    "att(/G98 G83 X20\\.000 Y20\\.000 Z5\\.000 I-4\\.000 J5/.test(fpk),'fagor : G83 I=-4 J=5 (golden)');",
    "att(!/G81 X/.test(fpk),'Q>0 fagor : G81 remplac\\u00e9 par G83');",
    // --- bibliothèque : Vc/fz -> S/F
    "const sf=faoToolSF({d:10,vc:250,fz:0.06,flutes:2});",
    "att(sf.s===7958&&sf.f===955,'biblio Vc250/fz0.06 D10 : S'+sf.s+' F'+sf.f);",
    // --- rapide machine + plongée % (P0-3)
    "att(faoRapide(job)===5000&&faoPlungePct(job)===30,'defauts posage : rapide 5000 + plongee 30 %');",
    "const sfP50=faoToolSF(job.tools[0],{plungePct:50});",
    "att(sfP50.plunge===Math.max(1,Math.round(sfP50.f*0.5)),'plongee 50 % de F : '+sfP50.plunge);",
    "const jobPl50=faoDefaultSetup();jobPl50.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};jobPl50.plungePct=50;",
    "jobPl50.ops=[{id:'p1',on:true,toolId:'T1',type:'drill',pts:[[20,20]],ztop:25,zbot:5}];",
    "const fp50=faoFmtF(faoToolSF(jobPl50.tools[0],jobPl50).plunge),fp30=faoFmtF(faoToolSF(jobPl50.tools[0],{plungePct:30}).plunge);",
    "att(fp50!==fp30,'50 % != 30 % ('+fp50+' vs '+fp30+')');",
    "const gP=faoPost(jobPl50,'siemens630').code;",
    "att(gP.indexOf(' F'+fp50)>=0,'post : plongee 50 % emise ('+fp50+')');",
    "att(gP.indexOf(' F'+fp30)<0,'post : plongee 30 % absente');",
    // --- multi-outils : 2 groupes, 2 changements
    "const jobB=faoDefaultJob();jobB.name='BI';jobB.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobB.ops=[{id:'a',on:true,toolId:'T1',type:'facing',z:25,ae:6},{id:'b',on:true,toolId:'T2',type:'facing',z:25,ae:4}];",
    "att(faoJobMoves(jobB).length===2,'multi-outils : 2 groupes');",
    "const sbi=faoPost(jobB,'siemens630').code;",
    "att((sbi.match(/\\nM6\\n/g)||[]).length===2,'multi-outils : 2x M6');",
    "att(/T2 D1/.test(sbi),'multi-outils : appel T2 D1');",
    // --- laisse ébauche
    "const cl=faoGenContour({x0:10,y0:10,x1:90,y1:70},5,0,{toolD:10,secu:30,laisse:0.5});",
    "att(cl.some(m=>!m.r&&Math.abs(m.x-95.5)<1e-9),'contour laisse 0.5 : X max 95.5');",
    "att(cl.filter(m=>!m.r).every(m=>m.z>=0.5-1e-9),'contour laisse 0.5 : fond Z>=0.5');",
    "const pl=faoGenPocket({x0:10,y0:10,x1:90,y1:70},25,5,{toolD:10,secu:30,ap:10,ae:5,laisse:0.5});",
    "att(pl.filter(m=>!m.r).every(m=>m.z>=5.5-1e-9),'poche laisse 0.5 : fond Z>=5.5');",
    // --- op désactivée ignorée partout
    "const jobC=JSON.parse(JSON.stringify(jobB));jobC.ops[0].on=false;",
    "att(faoJobMoves(jobC).length===1,'off : 1 seul groupe actif');",
    "doc.fao=jobC;",
    "att(faoStatsText().indexOf('1 op')===0,'off : stats 1 op active ('+faoStatsText()+')');",
    "att(faoPost(jobC,'siemens630').code.indexOf('T1 D1')<0,'off : T1 absent du G-code');",
    // --- migration ancien job plat (outil unique, 31t)
    "const keepFao=doc.fao;",
    "doc.fao={name:'VIEUX',wcs:'G54',post:'siemens630',tool:{num:1,d:12,s:6000,f:900,plunge:200},coolant:'flood',secu:5,marge:5,stock:{x0:0,y0:0,z0:0,x1:50,y1:50,z1:10},ops:[{type:'facing',z:10,ae:6}]};",
    "const rtM=faoRoot();",
    "att(rtM.setups.length===1,'migration : 1 posage enveloppe');",
    "const mig=rtM.setups[0];",
    "att(mig.tools.length===1&&mig.tools[0].d===12,'migration : outil unique -> biblio D12');",
    "att(mig.machine==='siemens630','migration : post -> machine');",
    "att(mig.ops[0].toolId===mig.tools[0].id&&mig.ops[0].on===true&&!!mig.ops[0].id,'migration : op recoit id+toolId+on');",
    "doc.fao=keepFao;",
    // --- origine pièce : G-code relatif au point de bloc
    "const jobO=faoDefaultSetup();jobO.stock={x0:10,y0:0,z0:0,x1:110,y1:80,z1:25};",
    "jobO.ops=[{id:'o1',on:true,toolId:'T1',type:'facing',z:25,ae:6}];",
    "const so=faoPost(jobO,'siemens630').code;",
    "att(/X-7\\.000/.test(so),'origine : X relatif (10-7-10=-7)');",
    "att(/Z0\\.000/.test(so),'origine : Z relatif (25-25=0)');",
    "att(/Origine G54/.test(so),'origine : commentaire G54');",
    "jobO.origin={preset:'top-C'};",
    "att(/dessus centre/.test(faoPost(jobO,'siemens630').code),'origine : preset centre');",
    // --- machine portée par le posage
    "const jobM=faoDefaultSetup();jobM.machine='fagor8065';jobM.stock={x0:0,y0:0,z0:0,x1:50,y1:50,z1:10};",
    "jobM.ops=[{id:'m1',on:true,toolId:'T1',type:'facing',z:10,ae:6}];",
    "att(faoPost(jobM).ext==='nc','machine du posage : fagor -> nc sans forcer');",
    // --- arbre FAO dédié
    "doc.fao={setups:[job],activeSetupId:job.id};",
    "faoRoot();",
    "document.getElementById('faoTree').children.length=0;",
    "faoRenderTree();",
    "att(document.getElementById('faoTree').children.length===5,'arbre FAO : 1 posage + 4 ops');",
    // --- fiches dans le panneau droit
    "const sid=faoSetup().id, oid=faoSetup().ops[0].id;",
    "sel={kind:'faoOp',id:oid,setup:sid};renderProps();",
    "att(document.getElementById('props').children.length>2,'fiche op dans panneau droit');",
    "sel={kind:'faoSetup',id:sid};renderProps();",
    "att(document.getElementById('props').children.length>2,'fiche posage dans panneau droit');",
    // --- fiche Ébauche 3D : sections lisibles, sans plantage (3 stratégies)
    "const r3=faoOpDefaults('rough3d');",
    "const c3=faoOpCardElement(faoSetup(),r3,0);",
    "att(c3.children.length>8,'fiche ebauche 3D : sections, vu '+c3.children.length);",
    "r3.strategy='adaptive';r3.ae=6;const c3b=faoOpCardElement(faoSetup(),r3,0);",
    "att(c3b.children.length>8,'fiche adaptive + alerte ae : sans plantage');",
    "r3.strategy='zigzag';const c3c=faoOpCardElement(faoSetup(),r3,0);",
    "att(c3c.children.length>8,'fiche zigzag : sans plantage');",
    "sel={kind:null,id:null};",
    // --- surépaisseurs radiale / axiale séparées
    "const pr=faoGenPocket({x0:10,y0:10,x1:90,y1:70},25,5,{toolD:10,secu:30,ap:10,ae:5,radial:1,axial:0});",
    "att(pr.filter(m=>!m.r).every(m=>m.z>=5-1e-9),'poche A0 : fond Z=5');",
    "att(pr.every(m=>m.x>=10.99&&m.x<=89.01&&m.y>=10.99&&m.y<=69.01),'poche R1 : XY dans [11,89]x[11,69]');",
    "const cr=faoGenContour({x0:10,y0:10,x1:90,y1:70},5,0,{toolD:10,secu:30,radial:0.5,axial:0});",
    "att(cr.some(m=>!m.r&&Math.abs(m.x-95.5)<1e-9),'contour R0.5 : X max 95.5');",
    "att(cr.filter(m=>!m.r).every(m=>Math.abs(m.z-0)<1e-9),'contour A0 : fond Z=0');",
    // --- migration laisse -> R/A (géodésique garde laisse)
    "const mOP={type:'pocket',laisse:0.5};faoSanitiseOps({tools:[{id:'T1'}],ops:[mOP]});",
    "att(mOP.radial===0.5&&mOP.axial===0.5&&mOP.laisse===undefined,'migration laisse -> R/A');",
    "const mOG={type:'geofinish',laisse:0.5};faoSanitiseOps({tools:[{id:'T1'}],ops:[mOG]});",
    "att(mOG.laisse===0.5&&mOG.radial===undefined,'geodesique : laisse conservee');",
    // --- plan de retrait : défaut dessus+25, utilisé entre outils
    "att(faoRetractZ(job)===50,'retrait auto = z1+25');",
    "att(/G0 Z25\\.000/.test(sbi),'retrait inter-outils (50-25=25 relatif)');",
    "jobB.retract=60;",
    "att(/G0 Z35\\.000/.test(faoPost(jobB,'siemens630').code),'retrait manuel 60 -> Z35');",
    "delete jobB.retract;",
    // --- Liang-Barsky + clipping
    "const lb=faoClipLB({x:-10,y:5},{x:10,y:5},{x0:0,y0:0,x1:10,y1:10});",
    "att(lb&&Math.abs(lb[0]-0.5)<1e-9&&Math.abs(lb[1]-1)<1e-9,'Liang-Barsky : entree 0.5');",
    "att(faoClipLB({x:-5,y:-5},{x:-1,y:-1},{x0:0,y0:0,x1:10,y1:10})===null,'LB : dehors -> null');",
    "const ei=faoEffLimit({limit:{mode:'rect',x0:0,y0:0,x1:20,y1:20,side:'in',extra:0}},10);",
    "att(ei&&ei.x0===5&&ei.x1===15,'limite in : retractee de r=5');",
    "att(faoEffLimit({limit:{mode:'rect',x0:0,y0:0,x1:10,y1:10,side:'out',extra:1}},10).x0===-6,'limite out+extra : -6');",
    "const jobL=faoDefaultSetup();jobL.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobL.ops=[{id:'l1',on:true,toolId:'T1',type:'facing',z:25,ae:6,limit:{mode:'rect',x0:0,y0:0,x1:50,y1:80,side:'center',extra:0}}];",
    "const lc=faoOpMoves(jobL.ops[0],jobL).filter(m=>!m.r);",
    "att(lc.length>0&&lc.every(m=>m.x>=-1e-9&&m.x<=50+1e-9),'clip facing : coupe dans [0,50]');",
    "const jobD=faoDefaultSetup();",
    "att(faoLimitDrillPts({pts:[[5,5],[99,99]],limit:{mode:'rect',x0:0,y0:0,x1:10,y1:10,side:'center',extra:0}},10).length===1,'perçage : trou hors limite écarté');",
    // --- chaînes tangentes : A-B tangents, C perpendiculaire
    "const ED=[{pts:[[0,0,0],[10,0,0]]},{pts:[[10,0,0],[20,0,0]]},{pts:[[20,0,0],[20,10,0]]}];",
    "att(JSON.stringify(faoTangentSet(ED,[0]).sort())===JSON.stringify([0,1]),'tangent : A+B');",
    "att(JSON.stringify(faoTangentSet(ED,[2]))===JSON.stringify([2]),'tangent : C seule');",
    // --- ordonnancement + boucle XY fermée (carré 10x10 désordonné)
    "const SQ=[{pts:[[10,0,5],[10,10,5]]},{pts:[[0,0,5],[10,0,5]]},{pts:[[0,10,5],[0,0,5]]},{pts:[[10,10,5],[0,10,5]]}];",
    "const CH=faoOrderEdges(SQ,[0,1,2,3]);",
    "att(CH.length===1&&CH[0].length===4,'ordre : 1 chaîne de 4');",
    "const LP=faoLoopFromChains(SQ,CH);",
    "att(LP.closed===true,'boucle : fermée');",
    "att(Math.abs(faoLoopArea(LP.loop)-100)<0.01,'boucle : aire 100');",
    // --- impair + distance + règle outil
    "const CAR=[[20,20],[80,20],[80,80],[20,80],[20,20]];",
    "att(faoPointInPoly(50,50,CAR)===true&&faoPointInPoly(10,10,CAR)===false,'impair : dedans/dehors');",
    "att(Math.abs(faoDistToPoly(50,50,CAR)-30)<1e-9,'distance : 30 au bord');",
    "att(faoLimInside(50,50,{loop:CAR,side:'in',extra:0},5)===true,'in : centre à 30>=5');",
    "att(faoLimInside(77,50,{loop:CAR,side:'in',extra:0},5)===false,'in : à 3<5 écarté');",
    "att(faoLimInside(83,50,{loop:CAR,side:'out',extra:0},5)===true,'out : à 3<=5 gardé');",
    "att(faoLimInside(90,50,{loop:CAR,side:'out',extra:0},5)===false,'out : à 10>5 écarté');",
    "att(faoLimInside(83,50,{loop:CAR,side:'center',extra:0},5)===false,'center : dehors écarté');",
    // --- clip polygone sur balayage : coupe dans le carré, précision 0.1
    "const MV=[{r:1,x:0,y:50,z:30},{r:1,x:0,y:50,z:25},{r:0,x:100,y:50,z:25}];",
    "const MC=faoClipMovesPoly(MV,{loop:CAR,side:'center',extra:0},5,30,2);",
    "const MCC=MC.filter(m=>!m.r);",
    "att(MCC.length>0&&MCC.every(m=>m.x>=20-0.15&&m.x<=80+0.15),'clip poly : coupe dans [20,80] a 0.15 pres');",
    "att(MCC.some(m=>Math.abs(m.x-20)<0.11),'clip poly : entrée à 0.1 près');",
    "att(MC.some(m=>m.r&&m.z===30),'clip poly : ré-entrée par sécu');",
    // --- dispatch chaîne + filtre perçage chaîne
    "const jobH=faoDefaultSetup();jobH.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobH.ops=[{id:'h1',on:true,toolId:'T1',type:'facing',z:25,ae:80,limit:{mode:'chain',loop:CAR,closed:true,nEdges:4,tangent:false,side:'center',extra:0}}];",
    "const mh=faoOpMoves(jobH.ops[0],jobH).filter(m=>!m.r);",
    "att(mh.length>0&&mh.every(m=>m.x>=-1e-9&&m.x<=80+1e-9&&m.y>=-1e-9&&m.y<=80+1e-9),'dispatch chaîne : coupe dans le carré');",
    "att(faoLimitDrillPts({pts:[[50,50],[5,5]],limit:{mode:'chain',loop:CAR,closed:true,side:'center',extra:0}},10).length===1,'perçage chaîne : 1/2 gardé');",
    // --- débourrage poche : hélice + pleine + tours, fond à 0.5
    "const DP=faoGenPocketRough({x0:0,y0:0,x1:100,y1:60},30,0,{toolD:10,ap:6,tour:2,ae:5,radial:0.5,axial:0.5,secu:35});",
    "att(DP.length>50,'débourrage : '+DP.length+' moves');",
    "att(DP.some(m=>!m.r&&m.z>24&&m.z<30),'débourrage : descente hélice');",
    "att(DP.some(m=>!m.r&&Math.abs(m.z-24)<1e-9&&Math.abs(m.x-50)<6),'débourrage : pleine passe à 24');",
    "const T28=DP.filter(m=>!m.r&&Math.abs(m.z-28)<1e-9);",
    "att(T28.length>0,'débourrage : tour à 28');",
    "att(T28.every(m=>Math.abs(m.x-5.5)<0.2||Math.abs(m.x-94.5)<0.2||Math.abs(m.y-5.5)<0.2||Math.abs(m.y-54.5)<0.2||Math.hypot(m.x-50,m.y-30)<=8),'débourrage : tour = périmètre (+ descente hélice)');",
    "att(DP.filter(m=>!m.r).every(m=>m.z>=0.5-1e-9),'débourrage : fond à 0.5 mini');",
    "att(DP.filter(m=>!m.r).every(m=>m.x>=5.5-1e-9&&m.x<=94.5+1e-9),'débourrage : radial 0.5 tenu');",
    // --- dispatch + fiche par défaut
    "const jobPct=faoDefaultSetup();",
    "const opP=faoOpDefaults('pocket3d');",
    "att(opP.type==='pocket3d'&&opP.ap===6&&opP.tour===2,'défauts débourrage : ap6 tours2');",
    "att(Array.isArray(faoOpMoves(Object.assign({},opP,{x0:0,y0:0,x1:100,y1:60,ztop:30,zbot:0}),jobPct)),'dispatch pocket3d');",
    // --- entrée en arc paroi : tangence à +Y des deux côtés
    "const endTan=function(L){",
    "  const cx=L.move.arc.i+L.sx, cy=L.move.arc.j+L.move.y;",
    "  const ex=L.move.x-cx, ey=L.move.y-cy, r=Math.hypot(ex,ey);",
    "  if(L.move.arc.cw)return [ey/r,-ex/r];",
    "  return [-ey/r,ex/r];",
    "};",
    "const LA=faoLeadArc(10,5,6,5,true,0);",
    "att(LA&&LA.sx===10&&LA.move.arc.cw===true,'lead-in gauche : départ 10, G2');",
    "att(Math.abs(endTan(LA)[0])<1e-9&&Math.abs(endTan(LA)[1]-1)<1e-9,'lead-in gauche : tangent +Y');",
    "const RA2=faoLeadArc(2,5,6,5,false,0);",
    "att(RA2&&RA2.sx===2&&RA2.move.arc.cw===false,'lead-in droite : départ 2, G3');",
    "att(Math.abs(endTan(RA2)[0])<1e-9&&Math.abs(endTan(RA2)[1]-1)<1e-9,'lead-in droite : tangent +Y');",
    "att(faoLeadArc(6,5,6,5,true,0)===null,'lead-in : M sur le mur -> null');",
    // --- arrondi 2.5D : poche avec arrondi -> arcs, sans -> aucun
    "const jobA=faoDefaultSetup();jobA.stock={x0:0,y0:0,z0:0,x1:100,y1:60,z1:20};",
    "const opA={id:'pa',on:true,toolId:'T1',type:'pocket',x0:10,y0:10,x1:90,y1:50,ztop:20,zbot:15,ap:5,ae:5,radial:0,axial:0,arrondi:3};",
    "att(faoOpMoves(opA,jobA).some(m=>!m.r&&m.arc),'poche arrondi 3 : arcs');",
    "const opB=Object.assign({},opA,{id:'pb',arrondi:0});",
    "att(!faoOpMoves(opB,jobA).some(m=>!m.r&&m.arc),'poche arrondi 0 : aucun arc');",
    // --- arrondi : L 10x10 R2 -> droite + arc + droite, centre (8,2)
    "const RD=faoRoundPath([{x:0,y:0,z:0},{x:10,y:0,z:0},{x:10,y:10,z:0}],2);",
    "att(RD.length===4&&!RD[1].arc&&!!RD[2].arc&&!RD[3].arc,'arrondi : G1+arc+G1');",
    "att(Math.abs(RD[1].x-8)<1e-9&&Math.abs(RD[2].x-10)<1e-9&&Math.abs(RD[2].y-2)<1e-9,'arrondi : points tangents (8,0)->(10,2)');",
    "att(RD[2].arc.cw===false&&Math.abs(RD[2].arc.i-0)<1e-9&&Math.abs(RD[2].arc.j-2)<1e-9,'arrondi : G3 centre relatif (0,2)');",
    // --- aligné : pas d'arc
    "const RL=faoRoundPath([{x:0,y:0,z:0},{x:5,y:0,z:0},{x:10,y:0,z:0}],2);",
    "att(RL.every(m=>!m.arc),'aligné : aucun arc');",
    // --- émission G2/G3 (les 2 CN en IJK)
    "att(faoArcWords({x:10,y:2,z:0,arc:{i:0,j:2,cw:false}},0,0,0)==='G3 X10.000 Y2.000 Z0.000 I0.000 J2.000','G3 IJK');",
    "att(faoArcWords({x:10,y:2,z:0,arc:{i:0,j:2,cw:true}},0,0,0).indexOf('G2 ')===0,'G2 horaire');",
    // --- estimation d'arc : quart de cercle R2 = PI
    "const EA=faoEstimate([{r:1,x:2,y:0,z:0},{r:0,x:0,y:2,z:0,arc:{i:-2,j:0,cw:false}}],1200,5000);",
    "att(Math.abs(EA.cut-Math.PI)<0.01,'arc estimé PI : '+EA.cut.toFixed(3));",
    // --- subdivision aperçu : sur le cercle, du début à la fin
    "const AS=faoArcSegs({x:2,y:0,z:0},{x:0,y:2,z:0,arc:{i:-2,j:0,cw:false}});",
    "att(AS.length>4,'subdivision : '+AS.length+' pts');",
    "att(AS.every(q=>Math.abs(Math.hypot(q[0],q[1])-2)<1e-9),'subdivision : rayon 2');",
    "att(Math.abs(AS[AS.length-1][0]-0)<1e-9&&Math.abs(AS[AS.length-1][1]-2)<1e-9,'subdivision : finit en (0,2)');",
    // --- persistance + non-rejeu
    "doc.fao=job;",
    "att(serialise().indexOf('\"fao\"')>=0,'serialise : doc.fao persiste');",
    "const v0=_docVersion;faoTouch();",
    "att(_docVersion===v0,'faoTouch : _docVersion inchange (aucun rejeu geometrique)');",
    // --- annulation documentaire des mods FAO (P0-2) : snapshot avant mutation, restaure a l'identique
    "const j0=JSON.stringify(doc.fao);",
    "faoSnapshot('test undo FAO');",
    "const stU=faoRoot();stU.setups[0].ops.push(faoOpDefaults('facing'));faoTouch();",
    "att(JSON.stringify(doc.fao)!==j0,'undo FAO : mutation effectuee');",
    "att(docUndo()===true,'undo FAO : docUndo ok');",
    "att(JSON.stringify(doc.fao)===j0,'undo FAO : etat restaure bit a bit');",
    "att(docRedo()===true,'redo FAO : docRedo ok');",
    "att(JSON.stringify(doc.fao)!==j0,'redo FAO : mutation re-appliquee');",
    // --- estimation : le rapide du posage pilote le temps annonce (P0-3)
    "doc.fao={setups:[Object.assign(faoDefaultSetup(),{name:'RAPTEST',stock:{x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},rapide:500,ops:[{id:'dr1',on:true,toolId:'T1',type:'drill',pts:[[10,10],[90,70]],ztop:25,zbot:5}]})],activeSetupId:null};",
    "const stA=faoStatsText();",
    "faoSetup().rapide=1000000;const stB=faoStatsText();",
    "att(stA&&stB&&stA!==stB,'stats : rapide du posage pris en compte ('+stA+' | '+stB+')');",
    "att(faoRapide({rapide:0})===5000&&faoRapide(null)===5000,'faoRapide : repli 5000 si invalide');",
    // --- P1-c : estimation à 2 nouveaux paramètres (accélération + changement d'outil)
    "att(faoAccel({accel:2500})===2500,'accel : 2500 lu');",
    "att(faoAccel({})===1000&&faoAccel(null)===1000&&faoAccel({accel:-4})===1000,'accel : defaut 1000 si absent/invalide');",
    "att(faoToolChg({toolChg:45})===45,'ch. outil : 45 s lu');",
    "att(faoToolChg({})===30&&faoToolChg(null)===30&&faoToolChg({toolChg:-1})===30,'ch. outil : defaut 30 s si absent/invalide');",
    "const EAc=faoEstimate([{r:1,x:0,y:0,z:0},{r:1,x:100,y:0,z:0}],1200,5000,1000);",
    "const tTheo=100/5000+(5000/60)/1000/60;",
    "att(Math.abs(EAc.tmin-tTheo)<1e-9,'accel : t = d/v + v/A ('+EAc.tmin.toFixed(6)+' vs '+tTheo.toFixed(6)+')');",
    "const EAfast=faoEstimate([{r:1,x:0,y:0,z:0},{r:1,x:100,y:0,z:0}],1200,5000,100000);",
    "att(EAfast.tmin<EAc.tmin,'accel : A elevee -> temps plus court');",
    "const EAold=faoEstimate([{r:1,x:0,y:0,z:0},{r:1,x:100,y:0,z:0}],1200,5000);",
    "att(Math.abs(EAold.tmin-EAc.tmin)<1e-12,'accel : repli 1000 sans 4e argument');",
    "const jobTC=faoDefaultSetup();jobTC.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobTC.tools=[{id:'T1',num:1,d:10,vc:250,fz:0.06,flutes:2},{id:'T2',num:2,d:6,vc:200,fz:0.05,flutes:2}];",
    "jobTC.ops=[{id:'t1',on:true,toolId:'T1',type:'facing',z:25,ae:6},{id:'t2',on:true,toolId:'T2',type:'facing',z:25,ae:4}];",
    "const sTc0=faoStats(Object.assign({},jobTC,{toolChg:0}));",
    "const sTc2=faoStats(Object.assign({},jobTC,{toolChg:120}));",
    "att(sTc0.groups===2,'stats : 2 groupes outil (T1 puis T2)');",
    "att(Math.abs((sTc2.tmin-sTc0.tmin)-2)<1e-9,'stats : 1 changement x 120 s = +2 min ('+(sTc2.tmin-sTc0.tmin).toFixed(3)+')');",
    "att(sTc2.tchg===2&&sTc0.tchg===0,'stats : tchg expose pour les tests');",
    // --- P2 : indexation 3+2 MVP (table C + B) — TRAORI Siemens, alerte Fagor
    "att(faoOrient({}).b===0&&faoOrient({}).c===0&&faoOrient(null).b===0,'orient : defaut 0/0');",
    "att(faoOrient({orient:{b:45.5,c:-90.123456}}).c===-90.123,'orient : arrondi 0.001');",
    "att(faoOrientOn({orient:{b:0,c:0}})===false&&faoOrientOn({orient:{b:0,c:30}})===true,'orient : detection active');",
    "const job32=faoDefaultSetup();job32.name='T32';job32.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "job32.ops=[{id:'a32',on:true,toolId:'T1',type:'facing',z:25,ae:6}];",
    "job32.orient={b:45,c:0};",
    "const g32=faoPost(job32,'siemens630').code;",
    "att(/TRAORI\\(1\\)/.test(g32),'siemens 3+2 : TRAORI(1) emis');",
    "att(/G0 B45\\.000 C0\\.000/.test(g32),'siemens 3+2 : positionnement B/C');",
    "att(g32.indexOf('TRAORI(1)')>0&&g32.indexOf('TRAORI(1)')<g32.indexOf('T1 D1'),'siemens 3+2 : TRAORI avant l outil');",
    "att(g32.indexOf('TRAFOOF')>0&&g32.indexOf('TRAFOOF')<g32.indexOf('M30'),'siemens 3+2 : TRAFOOF avant M30');",
    "att(faoPost(job32,'siemens630').warns.length===0,'siemens 3+2 : aucune alerte (TRAORI natif)');",
    "const g32f=faoPost(job32,'fagor8065');",
    "att(!/G0 B/.test(g32f.code),'fagor 3 axes : aucun B/C emis');",
    "att(!/TRAORI\\(1\\)/.test(g32f.code),'fagor 3 axes : pas de TRAORI');",
    "att(g32f.warns.length===1&&/machine 3 axes/.test(g32f.warns[0])&&/IGNOR/.test(g32f.warns[0]),'fagor 3 axes : alerte warns (indexation ignoree)');",
    "att(/ATTENTION/.test(g32f.code)&&/\\( 3\\+2 :/.test(g32f.code)&&/NON command/.test(g32f.code),'fagor 3 axes : alerte + commentaire en tete');",
    "job32.orient={b:0,c:0};",
    "const g32z=faoPost(job32,'siemens630');",
    "att(!/TRAORI|TRAFOOF/.test(g32z.code)&&!/B45\\.000/.test(g32z.code),'orient 0/0 : aucune trace 3+2');",
    "att(g32z.warns.length===0,'orient 0/0 : aucune alerte');",
    "delete job32.orient;const cAbs=faoPost(job32,'siemens630').code;job32.orient={b:0,c:0};",
    "att(cAbs===faoPost(job32,'siemens630').code,'orient 0/0 : programme identique a orient absent');",
    // --- P2 : rang 3+2 dans la fiche posage (saisie C + reset 3 axes)
    "const pc32=document.createElement('div');faoSetupFiche(pc32,faoSetup());",
    "let r32t=null;pc32.children.forEach(function(c){if(c.children&&c.children.length&&c.children[0].textContent==='3+2 B')r32t=c;});",
    "att(!!r32t,'UI fiche posage : rang 3+2 B/C');",
    "r32t.children[3].value='30';r32t.children[3].onchange();",
    "att(faoOrientOn(faoSetup())&&faoOrient(faoSetup()).c===30,'UI 3+2 : C=30 saisi');",
    "r32t.children[5].onclick();",
    "att(faoOrientOn(faoSetup())===false,'UI 3+2 : bouton 3 axes remet a plat');",
    // --- P2 : rejeu auto de la limite « chaîne » (ancres germes + stale)
    "const ceOp=faoSetup().ops[0];",
    "const ceMk=function(x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1;return {mid:[(x1+x2)/2,(y1+y2)/2,0],pts:[[x1,y1,0],[x2,y2,0]],len:Math.hypot(dx,dy),sharp:true};};",
    "const ceE=[ceMk(0,0,40,0),ceMk(40,0,40,30),ceMk(40,30,0,30),ceMk(0,30,0,0)];",
    "faoChainMode={setupId:faoSetup().id,opId:ceOp.id,edges:ceE,seeds:[0,1,2,3],tangent:false,sel:[0,1,2,3]};",
    "faoChainOk();",
    "att(ceOp.limit&&ceOp.limit.mode==='chain'&&ceOp.limit.anchors&&ceOp.limit.anchors.length===4,'capture chaine : 4 ancres sur les germes');",
    "att(ceOp.limit.stale===false,'capture chaine : stale=false');",
    "const ceL0=JSON.stringify(ceOp.limit.loop);",
    "att(faoLoopArea(ceOp.limit.loop)>1000,'capture chaine : boucle carree ~1200');",
    // (a) translation XY dans la tolérance -> la boucle suit
    "const ceE2=ceE.map(function(e){return {mid:[e.mid[0]+5,e.mid[1]-3,0],pts:e.pts.map(function(p){return [p[0]+5,p[1]-3,0];}),len:e.len,sharp:true};});",
    "const ceR1=faoChainRematch(ceOp,ceE2);",
    "att(ceR1.changed&&ceR1.stale===false&&ceR1.matched===4,'rejeu : 4/4 ancrees, boucle suivie');",
    "att(Math.abs(ceOp.limit.loop[0][0]-(JSON.parse(ceL0)[0][0]+5))<1e-6&&Math.abs(ceOp.limit.loop[0][1]-(JSON.parse(ceL0)[0][1]-3))<1e-6,'rejeu : boucle translatee (+5,-3)');",
    // (b) changement de Z seul -> XY identique -> pas de changement
    "const ceE3=ceE2.map(function(e){return {mid:[e.mid[0],e.mid[1],20],pts:e.pts.map(function(p){return [p[0],p[1],20];}),len:e.len,sharp:true};});",
    "const ceL1=JSON.stringify(ceOp.limit.loop);",
    "const ceR2=faoChainRematch(ceOp,ceE3);",
    "att(ceR2.changed===false&&ceR2.stale===false&&ceR2.matched===4,'rejeu : Z seul, boucle XY inchangee');",
    // (c) deplacement hors tolérance -> stale, boucle figee conservee
    "const ceE4=ceE.map(function(e){return {mid:[e.mid[0]+50,e.mid[1],0],pts:e.pts.map(function(p){return [p[0]+50,p[1],0];}),len:e.len,sharp:true};});",
    "const ceR3=faoChainRematch(ceOp,ceE4);",
    "att(ceR3.changed&&ceOp.limit.stale===true&&JSON.stringify(ceOp.limit.loop)===ceL1,'rejeu : +50 mm hors tol -> stale + boucle figee');",
    // (d) retour du modele d origine -> stale leve, boucle revenue
    "const ceR4=faoChainRematch(ceOp,ceE);",
    "att(ceR4.changed&&ceOp.limit.stale===false&&JSON.stringify(ceOp.limit.loop)===ceL0,'rejeu : retour modele -> stale leve + boucle restauree');",
    // (e) arete manquante -> tous les germes requis -> stale
    "const ceR5=faoChainRematch(ceOp,ceE.slice(0,3));",
    "att(ceR5.changed&&ceOp.limit.stale===true&&JSON.stringify(ceOp.limit.loop)===ceL0,'rejeu : arete disparue -> stale, boucle figee');",
    // (f) ancien document sans ancres -> ignore (comportement historique)
    "ceOp.limit={mode:'chain',loop:JSON.parse(ceL0),closed:true,nEdges:4,tangent:false,side:'center',extra:0};",
    "const ceR6=faoChainRematch(ceOp,ceE);",
    "att(ceR6.changed===false&&ceR6.skipped===true&&JSON.stringify(ceOp.limit.loop)===ceL0,'rejeu : sans ancres -> ignore');",
    // (g) tangente re-deduite depuis le germe (3 segments colineaires), boucle degeneree -> stale
    "const ceC=[ceMk(0,0,10,0),ceMk(10,0,20,0),ceMk(20,0,30,0)];",
    "ceOp.limit={mode:'chain',loop:[[0,0],[10,0]],closed:false,nEdges:1,tangent:true,side:'center',extra:0,anchors:[{m:[5,0,0],len:10}]};",
    "const ceR7=faoChainRematch(ceOp,ceC);",
    "att(ceR7.nSel===3&&ceR7.stale===true,'rejeu : tangent re-derinee (3) + boucle degeneree -> stale');",
    // (h) replay sans OCCT/solide exact -> no-op garde
    "att(faoChainReplay()===0,'rejeu : solide exact absent -> replay no-op (0)');",
    // (h2) câblage : la fin de rejeu (buildDone) appelle faoChainReplay
    "let ceBd=0;const ceOld=faoChainReplay;faoChainReplay=function(){ceBd++;return 0;};",
    "buildDone();",
    "faoChainReplay=ceOld;",
    "att(ceBd===1,'buildDone : branche faoChainReplay');",
    // (i) alerte fiche (stale) en mode selection de la fiche
    "const pcSt=document.createElement('div');faoSetupFiche(pcSt,faoSetup());",
    "const ceHasTxt=function(n,t){if(n.textContent&&n.textContent.indexOf(t)>=0)return true;const c=n.children||[];for(let i=0;i<c.length;i++)if(ceHasTxt(c[i],t))return true;return false;};",
    "att(ceHasTxt(pcSt,'re-s\\u00e9lectionnez la cha\\u00eene'),'fiche : alerte stale « re-s\\u00e9lectionnez la cha\\u00eene »');",
    // (i2) fiche : alerte 3+2 quand la machine est Fagor (3 axes)
    "const stF=faoSetup();const stFm=stF.machine, stFo=stF.orient;",
    "stF.machine='fagor8065';stF.orient={b:45,c:0};",
    "const pcFg=document.createElement('div');faoSetupFiche(pcFg,stF);",
    "att(ceHasTxt(pcFg,'machine 3 axes')&&ceHasTxt(pcFg,'IGNOR'),'fiche : alerte 3+2 sur Fagor (machine 3 axes)');",
    "stF.machine=stFm;stF.orient=stFo;",
    // (j) export : ATTENTION si une op a sa chaine obsolete
    "const jobS=faoDefaultSetup();jobS.name='TS';jobS.stock={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "jobS.ops=[{id:'as',on:true,toolId:'T1',type:'facing',z:25,ae:6,limit:{mode:'chain',loop:[[0,0],[60,0],[60,40]],closed:true,nEdges:3,tangent:false,side:'center',extra:0,stale:true}}];",
    "const ceh=faoPost(jobS,'siemens630');",
    "att(ceh.warns.length===1&&/cha\\u00eene/.test(ceh.warns[0])&&/ATTENTION/.test(ceh.code),'export : alerte limite chaine obsolete en tete de programme');",
    "delete ceOp.limit;",
    // --- 008 : plan sur la pièce (3+2) — normale -> angles B/C
    "const n0=faoOrientFromNormal(0,0,1);",
    "att(n0.b===0&&n0.c===0&&!n0.down,'plan : normale +Z -> B0 C0');",
    "const nX=faoOrientFromNormal(1,0,0);",
    "att(nX.b===-90&&nX.c===0&&!nX.down,'plan : normale +X -> B-90 C0 ('+nX.b+')');",
    "const nY=faoOrientFromNormal(0,1,0);",
    "att(nY.b===-90&&nY.c===-90&&!nY.down,'plan : normale +Y -> B-90 C-90 ('+nY.b+'/'+nY.c+')');",
    "att(faoOrientFromNormal(0,0,2).b===0&&faoOrientFromNormal(0,0,2).c===0,'plan : normale non unitaire normalisee');",
    "att(faoOrientFromNormal(0,0,-1).down===true,'plan : face vers le bas -> down=true');",
    "att(r32t.children[6]&&r32t.children[6].textContent==='Sur la pi\\u00e8ce','UI fiche : bouton Sur la pi\\u00e8ce (3+2)');",
    "faoChainMode=null;faoPlaneStart();",
    "att(faoPlanePick===null&&/aucun corps/.test(faceEl.textContent),'plan : sans corps -> garde + message');",
    "r32t.children[6].onclick();",
    "att(/aucun corps/.test(faceEl.textContent),'UI Sur la pi\\u00e8ce : garde sans corps');",
    "faoPlanePick={setupId:'x'};faoPlaneCancel();",
    "att(faoPlanePick===null,'plan : annulation (Echap) sort du mode');",
    "faoPlanePick={setupId:'x'};faoChainStart(null,'dr1');",
    "att(/quittez le mode/.test(faceEl.textContent),'plan : mode exclusif avec la selection de chaine');",
    "faoPlanePick=null;",
    // --- 008 : brut 3 sources (bodies / corps choisi / manuel)
    "const sKB=faoSetup();const sKo=sKB.stockSrc,sKold=sKB.stock;",
    "delete sKB.stockSrc;delete sKB.stockBody;",
    "const kB0=faoStock();",
    "att(kB0.x0===0&&kB0.x1===100&&kB0.y1===80,'brut : defaut bodies -> memoire (0..100)');",
    "sKB.stockSrc='manual';sKB.stock={x0:1,y0:2,z0:3,x1:11,y1:22,z1:23};",
    "const kM1=faoStock(),kM2=faoStock();",
    "att(kM1.x0===1&&kM1.y0===2&&kM1.z1===23&&kM1===kM2,'brut manuel : jamais recalcule (stabilite)');",
    "sKB.stockSrc='body';sKB.stockBody='zzz-inexistant';",
    "const kB2=faoStock();",
    "att(kB2.x0===1&&kB2.x1===11,'brut corps choisi : corps introuvable -> repli memoire');",
    "sKB.stockSrc=sKo;sKB.stock=sKold;if(sKo===undefined)delete sKB.stockSrc;",
    "att(faoStock().x0===0&&faoStock().x1===100,'brut : mode par defaut restaure');",
    // --- 008 : fiche « Brut · bridage » — Source, 6 champs manuels, hint corps absent
    "const pcB=document.createElement('div');faoSetupFiche(pcB,faoSetup());",
    "let rSrcT=null;pcB.children.forEach(function(c){if(c.children&&c.children.length&&c.children[0].textContent==='Source')rSrcT=c;});",
    "att(!!rSrcT,'UI brut : rang Source');",
    "const selS=rSrcT&&rSrcT.children[1];",
    "att(!!selS&&selS.tagName==='SELECT'&&selS.children.length===3,'UI brut : select 3 sources');",
    "selS.value='manual';selS.onchange();",
    "const pcM=document.createElement('div');faoSetupFiche(pcM,faoSetup());",
    "let rX0=null,rX1=null;pcM.children.forEach(function(c){if(!c.children||!c.children.length)return;if(c.children[0].textContent==='X0')rX0=c;if(c.children[0].textContent==='X1')rX1=c;});",
    "att(!!rX0&&!!rX1&&rX0.children.length===6&&rX1.children.length===6,'UI brut manuel : 2 rangs X0..Z0 / X1..Z1');",
    "att(!ceHasTxt(pcM,'MAJ brut'),'UI brut manuel : bouton MAJ masque');",
    "rX0.children[1].value='50';rX0.children[1].onchange();",
    "att(faoStock().x0===50,'UI brut manuel : saisie X0 appliquee');",
    "selS.value='bodies';selS.onchange();",
    "sKB.stockSrc='body';sKB.stockBody=null;",
    "const pcD=document.createElement('div');faoSetupFiche(pcD,faoSetup());",
    "att(ceHasTxt(pcD,'aucun corps visible'),'UI brut corps choisi : hint sans corps');",
    "sKB.stockSrc=sKo;sKB.stock=sKold;if(sKo===undefined)delete sKB.stockSrc;",
    // --- 008 : surfaçage — passes ET écart liés (couverture totale garantie)
    "const fkSt={x0:0,y0:0,z0:0,x1:100,y1:80,z1:25};",
    "att(faoFacingAe(fkSt,10,3)===45,'facing : ae pour np=3 -> 45 (H=90)');",
    "att(faoFacingAe(fkSt,10,1)===null&&faoFacingAe(fkSt,10,0)===null,'facing : np<2 -> null (pilotage par ae)');",
    "att(faoFacingCount(fkSt,10,45)===3,'facing : ae=45 -> 3 lignes');",
    "att(faoFacingCount(fkSt,10,6)===16,'facing : ae=6 -> 16 lignes (H=90)');",
    "const gNP=faoGenFacing(fkSt,{toolD:10,z:25,secu:30,np:3});",
    "const gNY=[];gNP.filter(function(m){return !m.r;}).forEach(function(m){if(gNY.indexOf(m.y)<0)gNY.push(m.y);});gNY.sort(function(a,b){return a-b;});",
    "att(gNY.length===3&&Math.abs(gNY[0]+5)<1e-6&&Math.abs(gNY[1]-40)<1e-6&&Math.abs(gNY[2]-85)<1e-6,'facing np=3 : lignes y=-5/40/85 (couverture totale)');",
    "const gNA=faoGenFacing(fkSt,{toolD:10,z:25,secu:30,ae:6});",
    "const gNAY=[];gNA.filter(function(m){return !m.r;}).forEach(function(m){if(gNAY.indexOf(m.y)<0)gNAY.push(m.y);});",
    "att(gNAY.length===faoFacingCount(fkSt,10,6),'facing ae=6 sans np : lignes = faoFacingCount');",
    "const fkS=faoSetup();",
    "const fkOp={id:'fk1',on:true,toolId:'T1',type:'facing',z:25,ae:6,np:3};",
    "const fkMY=[];faoOpMoves(fkOp,fkS).filter(function(m){return !m.r;}).forEach(function(m){if(fkMY.indexOf(m.y)<0)fkMY.push(m.y);});",
    "att(fkMY.length===3,'faoOpMoves : op.np=3 -> 3 niveaux');",
    "const fkOp2={id:'fk2',on:true,toolId:'T1',type:'facing',z:25,ae:6};",
    "const fkM2=[];faoOpMoves(fkOp2,fkS).filter(function(m){return !m.r;}).forEach(function(m){if(fkM2.indexOf(m.y)<0)fkM2.push(m.y);});",
    "att(fkM2.length===faoFacingCount(fkS.stock,10,6),'faoOpMoves : np absent -> ae=6 (compat)');",
    "fkS.ops.push({id:'fk3',on:true,toolId:'T1',type:'facing',z:25,ae:6});",
    "const fkI=fkS.ops.length-1;",
    "const cFk=faoOpCardElement(fkS,fkS.ops[fkI],fkI);",
    "const fNext=function(n,t){if(n.children){for(let i=0;i<n.children.length;i++){if(n.children[i].textContent===t&&n.children[i+1])return n.children[i+1];const r=fNext(n.children[i],t);if(r)return r;}}return null;};",
    "const npF=fNext(cFk,'Passes');const aeF=fNext(cFk,'\\u00e9cart');",
    "const fkD=(function(){const t=faoToolById(fkS,'T1');return t&&+t.d>0?+t.d:10;})();",
    // 011 : un SEUL paramètre de recouvrement XY (l'écart), lignes en lecture seule
    "att(!npF&&!!aeF,'UI surfaçage (011) : champ Passes retire, ecart seul');",
    "const nb6=faoFacingCount(fkS.stock,fkD,6);",
    "let lFk=null;(function w(n){if(n.children)n.children.forEach(function(ch){if(ch.textContent===nb6+' lignes')lFk=ch;w(ch);});})(cFk);",
    "att(!!lFk,'UI surfaçage (011) : lignes en lecture seule ('+nb6+' lignes)');",
    "aeF.value='7';aeF.onchange();",
    "att(fkS.ops[fkI].ae===7&&fkS.ops[fkI].np===null,'UI surfaçage : saisie ecart -> ae=7 respecte');",
    // ancien document piloté par « Passes » : lu tel quel, bascule à la saisie
    "fkS.ops[fkI].np=3;delete fkS.ops[fkI].ae;",
    "const cFk2=faoOpCardElement(fkS,fkS.ops[fkI],fkI);",
    "const aeF2=fNext(cFk2,'\\u00e9cart');",
    "const ae3=Math.round(faoFacingAe(fkS.stock,fkD,3)*1000)/1000;",
    "att(!!aeF2&&+aeF2.value===ae3,'UI surfaçage (011) : doc ancien np=3 -> ecart affiche ('+(aeF2?aeF2.value:'?')+', attendu '+ae3+')');",
    "let lFk2=null;(function w2(n){if(n.children)n.children.forEach(function(ch){if(ch.textContent==='3 lignes')lFk2=ch;w2(ch);});})(cFk2);",
    "att(!!lFk2,'UI surfaçage (011) : doc ancien -> 3 lignes affichees');",
    "aeF2.value='7';aeF2.onchange();",
    "att(fkS.ops[fkI].ae===7&&fkS.ops[fkI].np===null,'UI surfaçage : saisie ecart -> bascule en pilotage ecart (np efface)');",
    "fkS.ops.pop();",
    // --- 009 : corps-brut — invisible dès choisi + désignation via arbre 📦
    "doc.bodyVis={};",
    "doc.bodies.push({id:'stk1',name:'Barreau'},{id:'stk2',name:'Piece'});",
    "bodies.push({id:'stk1',name:'Barreau',mesh:{visible:true},visible:true,ghost:false,kind:'import',ref:'stk1'});",
    "bodies.push({id:'stk2',name:'Piece',mesh:{visible:true},visible:true,ghost:false,kind:'extrude',ref:'stk2'});",
    "const s9=faoSetup();delete s9.stockSrc;delete s9.stockBody;delete s9.stockBodyHid;",
    // (a) désignation -> corps choisi masqué, l'autre reste visible
    "faoStockBodySet('stk1');",
    "att(s9.stockSrc==='body'&&s9.stockBody==='stk1'&&s9.stockBodyHid===true,'brut auto : mode + corps choisi + flag masque');",
    "att(doc.bodyVis['stk1']===false&&bodies.find(b=>b.id==='stk1').visible===false,'brut auto : corps choisi invisible');",
    "att(bodies.find(b=>b.id==='stk2').visible===true,'brut auto : l autre corps reste visible');",
    // (b) changement de choix -> ancien restaure, nouveau masque
    "faoStockBodySet('stk2');",
    "att(bodies.find(b=>b.id==='stk1').visible===true&&doc.bodyVis['stk1']===undefined,'brut auto : ancien corps restaure');",
    "att(bodies.find(b=>b.id==='stk2').visible===false&&s9.stockBody==='stk2','brut auto : nouveau corps masque');",
    // (c) retrait -> mode bodies + restauration
    "faoStockBodySet(null);",
    "att(s9.stockSrc==='bodies'&&!s9.stockBody&&s9.stockBodyHid===false,'brut : retrait -> mode bodies');",
    "att(bodies.find(b=>b.id==='stk2').visible===true&&doc.bodyVis['stk2']===undefined,'brut : retrait -> corps visible');",
    // (d) garde : seul corps visible -> jamais masque (la vue ne se vide jamais)
    "bodies[0].visible=false;bodies[0].mesh.visible=false;",
    "faoStockBodySet('stk2');",
    "att(bodies.find(b=>b.id==='stk2').visible===true&&s9.stockBodyHid===false,'brut auto : seul corps -> non masque (vue preservee)');",
    "faoStockBodySet(null);",
    "bodies[0].visible=true;bodies[0].mesh.visible=true;",
    // (e) arbre : badge 📦 sur l'en-tête + clic = bascule désigner/retirer
    "renderTree();",
    "const tr9=document.getElementById('tree');",
    "let hdB=null;tr9.children.forEach(c=>{if(c.innerHTML&&c.innerHTML.indexOf('Barreau')>=0)hdB=c;});",
    "att(!!hdB&&hdB.innerHTML.indexOf('📦')>=0,'arbre : badge brut sur l en-tete corps');",
    "const tgt9={classList:{contains:function(c){return c==='stk';}}};",
    "delete s9.stockSrc;delete s9.stockBody;delete s9.stockBodyHid;",
    "hdB.onclick({target:tgt9});",
    "att(s9.stockSrc==='body'&&s9.stockBody==='stk1','arbre : clic 📦 designe le corps comme brut');",
    "att(bodies.find(b=>b.id==='stk1').visible===false,'arbre : clic 📦 masque le corps dans la vue');",
    "renderTree();tr9.children.forEach(c=>{if(c.innerHTML&&c.innerHTML.indexOf('Barreau')>=0)hdB=c;});",
    "att(hdB.innerHTML.indexOf('opacity:.35')<0,'arbre : badge plein une fois brut');",
    "hdB.onclick({target:tgt9});",
    "att(faoSetup().stockSrc==='bodies'&&!faoSetup().stockBody,'arbre : 2e clic 📦 -> retire le brut');",
    "att(bodies.find(b=>b.id==='stk1').visible===true,'arbre : retrait -> corps visible');",
    // (f) nettoyage pour la suite
    "delete s9.stockSrc;delete s9.stockBody;delete s9.stockBodyHid;",
    "doc.bodies.length=0;bodies.length=0;doc.bodyVis={};",
    // --- 010 : surfaçage — passes en Z / brut (ap CALCULÉ = (Z1−Z)/pz)
    "const zSt={x0:0,y0:0,z0:0,x1:100,y1:80,z1:40};",
    "const z10=faoGenFacing(zSt,{toolD:10,z:0,secu:30,ae:6,npz:4});",
    "const z10Z=[];z10.filter(function(m){return !m.r;}).forEach(function(m){if(z10Z.indexOf(m.z)<0)z10Z.push(m.z);});z10Z.sort(function(a,b){return a-b;});",
    "att(z10Z.length===4&&z10Z[0]===0&&z10Z[1]===10&&z10Z[2]===20&&z10Z[3]===30,'facing pz=4 : niveaux Z 0/10/20/30 (ap=(40−0)/4=10) : '+JSON.stringify(z10Z));",
    "const zN=faoGenFacing(zSt,{toolD:10,z:0,secu:30,ae:6});",
    "const zNZ=[];zN.filter(function(m){return !m.r;}).forEach(function(m){if(zNZ.indexOf(m.z)<0)zNZ.push(m.z);});",
    "att(zNZ.length===1&&zNZ[0]===0,'facing pz absent : passe unique a z=0');",
    "att(zN.length===gNA.length,'facing pz absent : structure identique au generateur historique');",
    "const z1=faoGenFacing(zSt,{toolD:10,z:0,secu:30,ae:6,npz:1});",
    "att(z1.length===zN.length,'facing pz=1 : identique a pz absent (mode historique)');",
    "const trZ=z10.filter(function(m,i){return i>0&&!m.r&&m.x===z10[i-1].x&&m.y===z10[i-1].y&&m.z!==z10[i-1].z;});",
    "att(trZ.length===3&&trZ.every(function(m){return m.y<=-5+1e-9||m.y>=85-1e-9;}),'facing pz : 3 plongees inter-niveaux en lisiere (hors matiere)');",
    "att(z10.filter(function(m){return !m.r;}).every(function(m){return m.z<=40+1e-9;}),'facing pz : aucune coupe au-dessus du brut');",
    "att(faoFacingAp(zSt,0,4)===10,'faoFacingAp : (40−0)/4 = 10');",
    "att(faoFacingAp(zSt,10,4)===7.5,'faoFacingAp : (40−10)/4 = 7.5');",
    "att(faoFacingAp(zSt,0,1)===null&&faoFacingAp(zSt,0,0)===null,'faoFacingAp : pz<2 -> null (pilotage passe unique)');",
    "att(faoFacingAp(zSt,40,4)===null&&faoFacingAp(zSt,45,4)===null,'faoFacingAp : z>=z1 -> null (rien a enlever)');",
    "const zM=faoOpMoves({id:'z1',on:true,toolId:'T1',type:'facing',z:0,ae:6,npz:4},fkS);",
    "const zMZ=[];zM.filter(function(m){return !m.r;}).forEach(function(m){if(zMZ.indexOf(m.z)<0)zMZ.push(m.z);});zMZ.sort(function(a,b){return a-b;});",
    "att(zMZ.length===4&&Math.abs(zMZ[0])<1e-9&&Math.abs(zMZ[3]-(25-25/4))<1e-9,'faoOpMoves : op.npz=4 -> 4 niveaux (25→0, ap=6.25) : '+JSON.stringify(zMZ));",
    "const zM0=faoOpMoves({id:'z2',on:true,toolId:'T1',type:'facing',z:0,ae:6},fkS);",
    "att(zM0.length===f.length,'faoOpMoves : npz absent -> golden facing intact ('+zM0.length+')');",
    // UI carte : champ pz + ap calculé affiché
    "fkS.ops.push({id:'fk10',on:true,toolId:'T1',type:'facing',z:0,ae:6});",
    "const fkI10=fkS.ops.length-1;",
    "const cF10=faoOpCardElement(fkS,fkS.ops[fkI10],fkI10);",
    "const pzF=fNext(cF10,'pz');",
    "att(!!pzF&&+pzF.value===1,'UI surfaçage : champ pz, defaut 1 passe');",
    "pzF.value='4';pzF.onchange();",
    "att(fkS.ops[fkI10].npz===4,'UI surfaçage : pz=4 -> op.npz');",
    "const cF10b=faoOpCardElement(fkS,fkS.ops[fkI10],fkI10);",
    "let apTxt='';(function walk(n){if(n.children)n.children.forEach(function(ch){if(ch.textContent&&ch.textContent.indexOf('ap ')===0)apTxt=ch.textContent;walk(ch);});})(cF10b);",
    "att(apTxt!=='ap —'&&apTxt.indexOf('ap ')===0,'UI surfaçage : ap calcule affiche ('+apTxt+')');",
    "pzF.value='1';pzF.onchange();",
    "att(fkS.ops[fkI10].npz===null,'UI surfaçage : pz=1 -> npz efface (mode historique)');",
    "fkS.ops.pop();",
    // --- 012 : viewer d'usinage (brut + outil, ▶/⏸/stop, traces cachées)
    "const vj={stock:{x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},secu:5,rapide:5000,ops:[{id:'v1',on:true,toolId:'T1',type:'facing',z:25,ae:6}],tools:[{id:'T1',d:10}]};",
    "const vwb=faoViewerBuild(vj);",
    "att(vwb.pts.length>10,'viewer : points du parcours ('+vwb.pts.length+')');",
    "att(vwb.times.length===vwb.pts.length&&vwb.times[0]===0,'viewer : temps alignes sur les points');",
    "att(vwb.T>0&&isFinite(vwb.T),'viewer : duree totale '+vwb.T.toFixed(1)+' s');",
    "const st12={pts:vwb.pts,dd:vwb.dd,times:vwb.times,idx:0,T:vwb.T};",
    "const q0=faoViewerSeek(st12,0);",
    "att(q0&&q0.i===0&&q0.f===0&&!q0.done,'viewer seek t=0 : depart');",
    "const qM=faoViewerSeek(st12,vwb.T/2);",
    "att(qM&&qM.f>=0&&qM.f<=1&&qM.i>=0&&qM.i<vwb.pts.length,'viewer seek 50% : i='+qM.i+' f='+qM.f.toFixed(2));",
    "const qE=faoViewerSeek(st12,vwb.T+5);",
    "att(qE&&qE.done===true,'viewer seek fin : arrivee');",
    "const st12b={pts:vwb.pts,dd:vwb.dd,times:vwb.times,idx:vwb.pts.length-1,T:vwb.T};",
    "const qB=faoViewerSeek(st12b,0);",
    "att(qB&&qB.i===0,'viewer seek arriere : idx reinitialise');",
    // aucune op active -> rien a jouer
    "const keep12=fkS.ops.length;fkS.ops.length=0;faoVw=null;faoViewerStart();",
    "att(faoVw===null,'viewer : sans op active, rien a jouer');",
    "fkS.ops.push({id:'v12',on:true,toolId:'T1',type:'facing',z:25,ae:6});",
    // ouverture : traces cachees + brut + outil + trace + barre + lecture
    "faoViewerStart();",
    "att(!!faoVw&&faoVw.playing===true,'viewer : ouvert + lecture demarree');",
    "att(!faoPrevGroup||faoPrevGroup.visible===false,'viewer : traces cachees');",
    "att(!!faoVw.stock&&!!faoVw.tool&&!!faoVw.line,'viewer : brut + outil + trace presents');",
    "att(!!faoVwBar&&faoVwBar.style.display==='flex','viewer : barre transport visible');",
    "const t12=faoVw.t;faoViewerAdvance(2);",
    "att(Math.abs(faoVw.t-(t12+2))<1e-6,'viewer : avance x1 (t='+faoVw.t.toFixed(2)+' s)');",
    "att(faoVw.drawn>=2,'viewer : trace dessinee (drawn='+faoVw.drawn+')');",
    "att(faoVw.tool.position.x>=-10&&faoVw.tool.position.x<=110&&faoVw.tool.position.y>=-10&&faoVw.tool.position.y<=90,'viewer : outil sur le parcours (x='+faoVw.tool.position.x.toFixed(1)+' y='+faoVw.tool.position.y.toFixed(1)+')');",
    // pause : le temps fige
    "faoViewerPause();const tP=faoVw.t;faoViewerAdvance(3);",
    "att(faoVw.t===tP&&faoVw.playing===false,'viewer : pause fige le temps');",
    // vitesse x5
    "faoVw.speed=5;faoVw.playing=true;faoViewerAdvance(1);",
    "att(Math.abs(faoVw.t-(tP+5))<1e-6,'viewer : vitesse x5');",
    "faoVw.speed=1;",
    // fin automatique en bout de parcours + trace complete
    "faoVw.playing=true;faoViewerAdvance(faoVw.T+60);",
    "att(faoVw.t===faoVw.T&&faoVw.playing===false,'viewer : fin auto en bout de parcours');",
    "att(faoVw.drawn===faoVw.pts.length,'viewer : trace entierement dessinee');",
    // stop : retour au depart
    "faoViewerStop();",
    "att(faoVw.t===0&&faoVw.playing===false&&faoVw.idx===0,'viewer : stop revient au depart');",
    // fermeture : traces restaurees, barre masquee, etat libere
    "faoViewerClose();",
    "att(faoVw===null,'viewer : ferme, etat libere');",
    "att(!faoPrevGroup||faoPrevGroup.visible!==false,'viewer : traces restaurees');",
    "att(!!faoVwBar&&faoVwBar.style.display==='none','viewer : barre masquee');",
    "fkS.ops.pop();",
    // --- 013 : sortie du mode lecture + matière usinée qui disparaît sous l'outil
    // (a) grille voxel pure (pas de scène)
    "const g13=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25});",
    "att(!!g13&&g13.n>0&&g13.n<=90000,'matiere : grille auto '+g13.nx+'x'+g13.ny+'x'+g13.nz+'='+g13.n+' (plafond ~40k)');",
    "att(g13.alive.length===g13.n&&g13.alive[0]===1&&g13.alive[g13.n-1]===1,'matiere : tous vivants au depart');",
    "const g13b=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},5);",
    "att(g13b.nx===20&&g13b.ny===16&&g13b.nz===5&&g13b.n===1600,'matiere : pas 5 -> 20x16x5=1600 ('+g13b.nx+'x'+g13b.ny+'x'+g13b.nz+')');",
    // (b) carve : sous l'outil meurt, hors rayon vit, sous la pointe vit
    "const g13c=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},5);",
    "const kA=faoMatterIdx(g13c,2,8,4),kB=faoMatterIdx(g13c,2,10,4),kC=faoMatterIdx(g13c,2,8,3);",
    "const ks13=faoMatterCarveSeg(g13c,10,40,25,90,40,25,5);",
    "att(ks13.length>0&&g13c.alive[kA]===0,'matiere carve : sous l outil tue ('+ks13.length+' voxels)');",
    "att(g13c.alive[kB]===1,'matiere carve : hors rayon (y=52.5) reste');",
    "att(g13c.alive[kC]===1,'matiere carve : sous la pointe (z=17.5) reste');",
    "att(faoMatterCarveSeg(g13c,10,40,25,90,40,25,0).length===0,'matiere carve : rayon 0 -> rien');",
    // (c) rapide = rien ; segment en cours inclus dans le rattrapage 0->t
    "const g13d=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},5);",
    "const kR=faoMatterCarveTo(g13d,[{x:10,y:40,z:25,r:1},{x:90,y:40,z:25,r:1}],[10,10],[0,10],10);",
    "att(kR.length===0,'matiere : G0 rapide n enleve rien');",
    "const g13e=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},5);",
    "const kT=faoMatterCarveTo(g13e,[{x:10,y:40,z:25,r:0},{x:90,y:40,z:25,r:0}],[10,10],[0,10],2);",
    "att(kT.length>0,'matiere : segment en cours a t=2 coupe deja ('+kT.length+' voxels)');",
    "const g13f=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},5);",
    "att(faoMatterCarveTo(g13f,[{x:10,y:40,z:25,r:0},{x:90,y:40,z:25,r:0}],[10,10],[0,10],-1).length===0,'matiere : avant t=0 rien');",
    // (d) mode lecture : matière créée + corps masqués + avance enlève la matière
    "fkS.ops.length=0;faoVw=null;faoPrevOn=true;",
    "fkS.ops.push({id:'v13',on:true,toolId:'T1',type:'facing',z:25,ae:6});",
    "bodies.push({id:'vh1',name:'VH',mesh:{visible:true},visible:true,ghost:false,kind:'import',ref:'vh1'});",
    "att(faoViewerStart()===true,'013 : lecture demarree');",
    "att(!!faoVw.matter&&!!faoVw.matterGrid&&faoVw.matterOn===true,'013 : matiere voxel creee ('+(faoVw.matterGrid?faoVw.matterGrid.n:'?')+' voxels)');",
    "att(faoVw.hideBodies.length===1&&faoVw.hideBodies[0].mesh.visible===false,'013 : corps masques pendant la matiere');",
    "let alive0=0;for(let i=0;i<faoVw.matterGrid.n;i++)alive0+=faoVw.matterGrid.alive[i];",
    "faoViewerAdvance(10);",
    "let alive1=0;for(let i=0;i<faoVw.matterGrid.n;i++)alive1+=faoVw.matterGrid.alive[i];",
    "att(alive1<alive0&&alive1>0,'013 : la matiere disparaît sous l outil ('+alive0+' -> '+alive1+')');",
    "faoViewerStop();",
    "let alive2=0;for(let i=0;i<faoVw.matterGrid.n;i++)alive2+=faoVw.matterGrid.alive[i];",
    "att(alive2===alive0,'013 : stop = matiere entierement restauree ('+alive2+'/'+alive0+')');",
    // (e) toggle matière OFF -> corps ré-affichés ; ON -> reconstruite
    "faoViewerMatterToggle();",
    "att(faoVw.matterOn===false&&!faoVw.matter&&!faoVw.matterGrid,'013 : toggle OFF = matiere retiree');",
    "att(faoVw.hideBodies.length===0&&bodies[0].mesh.visible===true,'013 : toggle OFF = corps re-affiches');",
    "faoViewerMatterToggle();",
    "att(faoVw.matterOn===true&&!!faoVw.matter&&!!faoVw.matterGrid,'013 : toggle ON = matiere reconstruite');",
    "att(bodies[0].mesh.visible===false,'013 : toggle ON = corps masques');",
    // (f) sortie du mode lecture = TOUT retiré
    "const v13vw=faoVw;",
    "faoViewerClose();",
    "att(faoVw===null,'013 : sortie du mode = etat libere');",
    "att(v13vw.matter===null&&v13vw.matterGrid===null,'013 : sortie = matiere enlevee');",
    "att(v13vw.hideBodies.length===0&&bodies[0].mesh.visible===true,'013 : sortie = corps re-affiches');",
    "att(!faoPrevGroup||faoPrevGroup.visible!==false,'013 : sortie = traces re-affichees');",
    "att(!!faoVwBar&&faoVwBar.style.display==='none','013 : sortie = barre masquee');",
    // (g) bouton fiche : bascule ouvrir/fermer + libellé explicite
    "const pc13=document.createElement('div');faoSetupFiche(pc13,fkS);",
    "att(!!faoVwBtn&&faoVwBtn.textContent.indexOf('Usinage')>=0&&faoVwBtn.textContent.indexOf('Quitter')<0,'013 : bouton hors mode = ▶ Usinage');",
    "const on13=faoViewerToggle();",
    "att(on13===true&&!!faoVw&&faoVwBtn.textContent.indexOf('Quitter')>=0,'013 : toggle ouvre + libelle Quitter');",
    "const off13=faoViewerToggle();",
    "att(off13===false&&!faoVw&&faoVwBtn.textContent.indexOf('Quitter')<0,'013 : toggle ferme + libelle ▶ Usinage');",
    "att(bodies[0].mesh.visible===true&&!faoVw,'013 : bascule nettoie corps + etat');",
    // (h) « Générer + aperçu » ré-affiche TOUJOURS (un ancien Masquer ne bloque plus)
    "faoPrevOn=false;const n13=faoPreviewGenerate();",
    "att(faoPrevOn===true,'013 : Générer + aperçu force l affichage des traces');",
    "att(n13>0&&(!faoPrevGroup||faoPrevGroup.visible===true),'013 : traces regenerees visibles ('+n13+' moves)');",
    "bodies.length=0;doc.bodies.length=0;doc.bodyVis={};",
    // --- 014 : fenêtre flottante bibliothèque d'outils (bouton fiche/arbre, ✕, Échap)
    "if(faoVw)faoViewerClose();",
    "att(faoToolsWindowOpen()===true,'014 : fenetre ouverte');",
    "const tw14=faoToolsWin;",
    "att(!!tw14&&tw14.style.display==='block','014 : fenetre visible');",
    "att(!!faoToolsWinT&&faoToolsWinT.textContent.indexOf('Outils · ')===0,'014 : titre = posage actif ('+faoToolsWinT.textContent+')');",
    "att(ceHasTxt(faoToolsWinBody,'Outils ('),'014 : contenu = biblio outils');",
    "const nb014=(faoSetup().tools||[]).length;",
    "let bA14=null;(function w14(n){if(n.textContent==='+ Outil')bA14=n;if(n.children)n.children.forEach(w14);})(faoToolsWinBody);",
    "att(!!bA14,'014 : bouton + Outil dans la fenetre');",
    "bA14.onclick();",
    "att(faoSetup().tools.length===nb014+1,'014 : + Outil ajoute ('+faoSetup().tools.length+'/'+nb014+')');",
    "faoToolsWinX.onclick();",
    "att(faoToolsWin===null&&tw14.style.display==='none','014 : bouton X ferme');",
    "faoToolsWindowOpen();window.dispatchEvent({type:'keydown',key:'Escape'});",
    "att(faoToolsWin===null,'014 : Echap ferme la fenetre');",
    "faoViewerStart();att(!!faoVw,'014 : viewer ouvert');",
    "faoToolsWindowOpen();window.dispatchEvent({type:'keydown',key:'Escape'});",
    "att(faoToolsWin===null&&!!faoVw,'014 : Echap ferme la fenetre AVANT le viewer');",
    "window.dispatchEvent({type:'keydown',key:'Escape'});",
    "att(faoVw===null,'014 : 2e Echap quitte le viewer');",
    "const pc14=document.createElement('div');faoSetupFiche(pc14,faoSetup());",
    "let bF14=null;(function w14b(n){if(n.textContent==='Outils')bF14=n;if(n.children)n.children.forEach(w14b);})(pc14);",
    "att(!!bF14,'014 : bouton Outils dans la fiche posage');",
    "bF14.onclick();",
    "att(!!faoToolsWin&&faoToolsWin.style.display==='block','014 : bouton fiche ouvre');",
    "bF14.onclick();",
    "att(faoToolsWin===null,'014 : bouton fiche bascule (2e clic = ferme)');",
    "let bTr14=null;(function w14c(n){if(n&&n.id==='faoToolsBtn')bTr14=n;if(n&&n.children)n.children.forEach(w14c);})(faoTreeWrapEl);",
    "att(!!bTr14,'014 : bouton Outils dans l arbre FAO');",
    "bTr14.onclick();",
    "att(!!faoToolsWin,'014 : bouton arbre ouvre la fenetre');",
    "faoToolsWindowClose();",
    // --- 015 : matière = surface Z-map pleine (colonnes jointives, un seul mesh)
    "faoVw=null;faoPrevOn=true;",
    "att(faoViewerStart()===true,'015 : lecture demarree');",
    "const g15=faoVw.matterGrid,nc15=g15.nx*g15.ny,full15=g15.oz+g15.nz*g15.pas;",
    "att(!!faoVw.matter&&!!faoVw.mTops&&!!faoVw.mArr,'015 : surface Z-map creee');",
    "att(faoVw.mTops.length===nc15,'015 : une hauteur par colonne ('+nc15+')');",
    "att(faoVw.mArr.length===(nc15*30+6)*3,'015 : geo = 30 verts/colonne + fond ('+faoVw.mArr.length+' floats)');",
    "att(Math.abs(faoVw.mTops[0]-full15)<1e-4&&Math.abs(faoVw.mTops[nc15-1]-full15)<1e-4,'015 : brut plein au depart ('+full15+')');",
    "faoViewerAdvance(10);",
    "let mn15=full15,pn15=0;for(let i=0;i<nc15;i++){ if(faoVw.mTops[i]<mn15)mn15=faoVw.mTops[i]; if(full15-faoVw.mTops[i]<1e-4)pn15++; }",
    "att(mn15<full15-1e-4,'015 : colonnes entamees sous l outil ('+mn15+' < '+full15+')');",
    "att(pn15>0,'015 : des colonnes restent pleines ('+pn15+'/'+nc15+')');",
    "faoViewerStop();",
    "let ok15=true;for(let i=0;i<faoVw.mTops.length;i++)if(Math.abs(faoVw.mTops[i]-full15)>=1e-4)ok15=false;",
    "att(ok15&&faoVw.mTops.length===nc15,'015 : stop = surface restauree pleine');",
    "faoViewerMatterToggle();",
    "att(faoVw.matterOn===false&&!faoVw.mTops&&!faoVw.mArr&&faoVw.matter===null,'015 : toggle OFF = surface retiree');",
    "faoViewerMatterToggle();",
    "att(faoVw.matterOn===true&&!!faoVw.mTops&&faoVw.mTops.length===nc15&&!!faoVw.mArr,'015 : toggle ON = surface reconstruite');",
    "const v15vw=faoVw;faoViewerClose();",
    "att(v15vw.matter===null&&v15vw.mTops===null&&v15vw.mArr===null&&v15vw.matterGrid===null,'015 : sortie = etat libere');",
    // --- 016 : Z-map continue = cote de coupe exacte (retour : « Z pas colle a l'outil »)
    "const g16=faoMatterGrid({x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},5);",
    "att(!!g16.h&&g16.h.length===g16.nx*g16.ny,'016 : grille = une hauteur par colonne ('+g16.h.length+')');",
    "const c16=8*g16.nx+2,c16b=10*g16.nx+10;",
    "att(Math.abs(faoMatterColTop(g16,c16)-25)<1e-3,'016 : plein au depart ('+faoMatterColTop(g16,c16)+')');",
    "faoMatterCarveSeg(g16,10,40,17.5,90,40,17.5,5);",
    "att(Math.abs(faoMatterColTop(g16,c16)-17.5)<1e-3,'016 : surface = cote exacte 17.5 ('+faoMatterColTop(g16,c16)+')');",
    "att(Math.abs(faoMatterColTop(g16,c16b)-25)<1e-3,'016 : hors rayon reste plein');",
    "faoMatterCarveSeg(g16,10,40,12,90,40,12,5);",
    "att(Math.abs(faoMatterColTop(g16,c16)-12)<1e-3,'016 : 2e passe descend a 12 ('+faoMatterColTop(g16,c16)+')');",
    "att(g16.alive[faoMatterIdx(g16,2,8,0)]===1,'016 : vivant sous la pointe (voxels inchanges)');",
    // --- P1-b : UI pilotée dans appvm (œil, ↑/↓, +op, export)
    "doc.fao={setups:[Object.assign(faoDefaultSetup(),{name:'UITEST',stock:{x0:0,y0:0,z0:0,x1:100,y1:80,z1:25},ops:[{id:'u1',on:true,toolId:'T1',type:'facing',z:25,ae:6},{id:'u2',on:true,toolId:'T1',type:'drill',pts:[[20,20]],ztop:25,zbot:5}]})],activeSetupId:null};",
    "sel={kind:null,id:null};document.getElementById('faoTree').children.length=0;faoRenderTree();",
    "const tr=document.getElementById('faoTree');",
    "att(tr.children.length===3,'UI oeil : arbre = posage + 2 ops');",
    "tr.children[1].children[0].onclick({stopPropagation(){}});",
    "att(faoSetup().ops[0].on===false,'UI oeil : 1er clic = operation desactivee');",
    "att(faoStatsText().indexOf('1 op')===0,'UI oeil : stats a 1 op ('+faoStatsText().slice(0,20)+')');",
    "tr.children[1].children[0].onclick({stopPropagation(){}});",
    "att(faoSetup().ops[0].on===true,'UI oeil : 2e clic = reactivee');",
    "const uS=faoSetup();",
    "const cardF=faoOpCardElement(uS,uS.ops[0],0);",
    "const dnF=cardF.children[0].children[4];",
    "att(dnF&&dnF.textContent==='\\u2193','UI fiche : bouton bas');",
    "dnF.onclick();",
    "att(uS.ops[0].type==='drill','UI \\u2193 : ordre bascule');",
    "att(docUndo()===true,'UI \\u2193 : annulable (snapshot avant mutation)');",
    "att(faoSetup().ops[0].type==='facing','UI \\u2193 : ordre restaure apres annulation');",
    "const cUp1=faoOpCardElement(faoSetup(),faoSetup().ops[0],0);",
    "cUp1.children[0].children[3].onclick();",
    "att(faoSetup().ops[0].type==='facing','UI \\u2191 en tete : sans effet (limite)');",
    "const cUp2=faoOpCardElement(faoSetup(),faoSetup().ops[1],1);",
    "cUp2.children[0].children[3].onclick();",
    "att(faoSetup().ops[0].type==='drill','UI \\u2191 : per\\u00e7age remonte en tete');",
    "const pc=document.createElement('div');faoSetupFiche(pc,faoSetup());",
    "let addRow=null;pc.children.forEach(function(c){if(c.children&&c.children.length&&String(c.children[0].textContent||'').indexOf('+')===0)addRow=c;});",
    "att(!!addRow&&addRow.children.length>=7,'UI fiche : rang des 7 boutons +op');",
    "const nB=faoSetup().ops.length;",
    "addRow.children[3].onclick();",
    "att(faoSetup().ops.length===nB+1,'UI +op : operation ajoutee');",
    "att(faoSetup().ops[nB].type==='drill','UI +op : type choisi (+ Per\\u00e7age)');",
    "globalThis.Blob=class{constructor(p){this.parts=Array.isArray(p)?p:[];this.type='';}};",
    "globalThis.__exp='';",
    "globalThis.URL={createObjectURL:function(b){globalThis.__exp=(b&&b.parts||[]).join('');return 'blob:ui';},revokeObjectURL:function(){}};",
    "const __cr=document.createElement;let __dl='';document.createElement=function(t){const n=__cr(t);if(String(t).toLowerCase()==='a'){n.click=function(){__dl=n.download;};}return n;};",
    "let expB=null;pc.children.forEach(function(c){if(c.children)c.children.forEach(function(k){if(k.textContent==='Exporter G-code')expB=k;});});",
    "att(!!expB,'UI fiche : bouton Exporter G-code');",
    "expB.onclick();",
    "att(globalThis.__exp.length>100,'UI export : G-code produit ('+globalThis.__exp.length+' car.)');",
    "att(/M30/.test(globalThis.__exp),'UI export : pied M30');",
    "att(/CYCLE81/.test(globalThis.__exp),'UI export : per\\u00e7age en cycle dialecte');",
    "att(/UITEST\\.mpf$/.test(__dl),'UI export : nom fichier ('+__dl+')');",
    "document.createElement=__cr;",
    "if(ATT.length){p('');p('ECHECS ('+ATT.length+') :');ATT.forEach(m=>p('  x '+m));}",
    "else p('TOUT EST CONFORME');",
    "p('facing='+f.length+' pocket='+pk.length+' contour='+ct.length+' drill='+dr.length);",
    "p('G1 siemens='+(s630.code.match(/\\nG1 /g)||[]).length+' G1 fagor='+(fg.code.match(/ G1 /g)||[]).length);",
    "return P.join(String.fromCharCode(10));"
  ].join('\n');
  const r=await vm.runInContext('(async()=>{'+R+'})()',ctx,{filename:'fao.js'});
  console.log(r);
  process.exit(/ECHECS|  x /.test(r)?1:0);
})().catch(e=>{console.error('ECHEC',String((e&&e.message)||e).slice(0,500));process.exit(1);});
