// FAO 2026-10-08-003 — zone INTÉRIEURE (îlot à préserver) : on usine ENTRE
// la zone extérieure (op.limit) et l'îlot (op.limit2). Règle outil fixée
// « hors de l'îlot » : contour dilaté de r + Marge (side 'out' interne),
// on garde le COMPLÉMENT. Même forme que la zone extérieure (rect ou chaîne
// d'arêtes), clip composé partout (parcours, garde-fou zone, affichage,
// perçage), re-brançage auto des ancres à chaque rejeu.
//
// Fixture : bloc 80x60x18 + poche ouverte x[10,70] y[10,50] fond z=4
// (même maillage manifold que test_fao_escargot) pour le dispatch complet.
const {loadApp}=require('./appvm.cjs');
const vm=require('vm');
(async()=>{
  const {ctx}=loadApp();
  const R=[
    "const P=[];const p=s=>P.push(String(s));",
    "const ATT=[];const att=(ok,msg)=>{if(!ok)ATT.push(msg);};",
    "const J=JSON.stringify;",
    // ================= 1. faoLimit2R : dilatation r+marge ===================
    "const R1=faoLimit2R({mode:'rect',x0:0,y0:0,x1:10,y1:10,extra:0},10);",
    "att(R1&&R1.x0===-5&&R1.x1===15&&R1.y0===-5&&R1.y1===15,'limit2 rect : dilate de r=5 ( '+R1.x0+'..'+R1.x1+' )');",
    "const R2=faoLimit2R({mode:'rect',x0:0,y0:0,x1:10,y1:10,extra:2},10);",
    "att(R2&&R2.x0===-7&&R2.x1===17,'limit2 rect : marge +2 -> k=7');",
    "const R3=faoLimit2R({mode:'rect',x0:0,y0:0,x1:10,y1:10,extra:-20},10);",
    "att(!!R3&&R3.x1>R3.x0,'limit2 rect : marge tres negative clampée (pas d oubli silencieux)');",
    "att(faoLimit2R({mode:'chain'},10)===null,'limit2 : non-rect -> null (branche chaine ailleurs)');",
    // ================= 2. clip rect en COMPLÉMENT ===========================
    "const isl={x0:0,y0:0,x1:10,y1:10};",
    "const mvX=[{r:1,x:-5,y:5,z:8},{r:0,x:-5,y:5,z:1},{r:0,x:15,y:5,z:1},{r:0,x:15,y:15,z:1}];",
    "const outOut=faoClipMovesXY(mvX,isl,8,true);",
    "const cutsOut=outOut.filter(function(m){return !m.r;});",
    "att(cutsOut.length>0,'clip rect : pieces dehors conservees ('+cutsOut.length+' coupes)');",
    "att(cutsOut.every(function(m){return !(m.x>0.0001&&m.x<9.9999&&m.y>0.0001&&m.y<9.9999);}),",
    "  'clip rect : AUCUNE coupe strictement dans l îlot');",
    "att(cutsOut.some(function(m){return m.x<0;})&&cutsOut.some(function(m){return m.x>10;}),",
    "  'clip rect : les deux cotes de l îlot usines');",
    "att(outOut.filter(function(m){return m.r&&m.z===8;}).length>=2,'clip rect : re-entry securisee (2 remontees secu)');",
    "const outIn=faoClipMovesXY(mvX,isl,8,false);",
    "const cutsIn=outIn.filter(function(m){return !m.r;});",
    "att(cutsIn.length>0&&cutsIn.every(function(m){return m.x>=-0.0001&&m.x<=10.0001;}),",
    "  'regression : clip normal (sans invert) garde bien LE DEDANS');",
    // ================= 3. clip chaine en COMPLÉMENT =========================
    "const loop=[[20,20],[30,20],[30,30],[20,30],[20,20]];",
    "const L2c={mode:'chain',loop:loop,side:'out',extra:0};",
    "const at2=function(x,y){return !faoLimInside(x,y,L2c,1);};",
    "const mvP=[{r:1,x:15,y:25,z:8},{r:0,x:15,y:25,z:1},{r:0,x:35,y:25,z:1},{r:0,x:35,y:35,z:1}];",
    "const outP=faoClipMovesPoly(mvP,L2c,1,8,2,at2);",
    "const cutsP=outP.filter(function(m){return !m.r;});",
    "att(cutsP.length>0,'clip chaine : pieces conservees ('+cutsP.length+' coupes)');",
    "att(cutsP.every(function(m){return !faoPointInPoly(m.x,m.y,loop);}),",
    "  'clip chaine : AUCUNE coupe dans le polygone de l îlot');",
    "att(cutsP.some(function(m){return m.x<20;})&&cutsP.some(function(m){return m.x>30;}),",
    "  'clip chaine : usinage des deux cotes');",
    // ================= 4. faoZoneCtx composé ================================
    "const job=faoDefaultJob();",
    "job.stock={x0:-5,y0:-5,z0:0,x1:85,y1:65,z1:18};",
    "const opC={id:'z2',on:true,toolId:'T1',type:'pocket',ap:4,ae:5,ztop:18,zbot:4,",
    "  limit:{mode:'rect',x0:0,y0:0,x1:100,y1:100,side:'center',extra:0},",
    "  limit2:{mode:'rect',x0:40,y0:40,x1:60,y1:60,extra:0}};",
    "const cx=faoZoneCtx(opC,job);",
    "att(!!cx,'ctx : zone ext + îlot -> un contexte');",
    "att(cx&&cx.R&&cx.R2,'ctx : R (ext) et R2 (îlot) presents');",
    "if(cx){",
    "  att(cx.at(10,10)===true,'ctx : dedans ext, hors îlot -> usinable');",
    "  att(cx.at(50,50)===false,'ctx : dans l îlot -> NON usinable');",
    "  att(cx.at(-1,-1)===false,'ctx : hors zone ext -> NON usinable');",
    "  att(cx.at(70,50)===true,'ctx : dans ext, hors îlot (îlot dilate a 35..65) -> usinable');",
    "  att(cx.cross({x:10,y:50},{x:50,y:50})===true,'ctx : traverse la frontiere de l îlot -> cross');",
    "  att(cx.cross({x:0,y:0},{x:10,y:10})===false,'ctx : trajet interieur sans frontiere -> pas de cross');",
    "}",
    "const opOnly={id:'z2b',toolId:'T1',type:'pocket',limit2:opC.limit2};",
    "const cx2=faoZoneCtx(opOnly,job);",
    "att(!!cx2&&!cx2.lim&&cx2.R2&&cx2.at(50,50)===false&&cx2.at(10,10)===true,'ctx : îlot SEUL (pas de zone ext)');",
    "att(faoZoneCtx({id:'z2c',toolId:'T1',type:'pocket'},job)===null,'ctx : sans zone -> null (inchange)');",
    // ================= 5. faoZoneCuts de bout en bout =======================
    "const mvZ=[{r:1,x:0,y:0,z:8},{r:0,x:0,y:0,z:1},{r:0,x:100,y:0,z:1},",
    "  {r:0,x:100,y:100,z:1},{r:0,x:0,y:100,z:1},{r:0,x:0,y:50,z:1},{r:0,x:100,y:50,z:1}];",
    "const zc=faoZoneCuts(mvZ,opC,job,8);",
    "const zcCuts=zc.filter(function(m){return !m.r;});",
    "att(zcCuts.length>0,'ZoneCuts : coupe conservee ('+zcCuts.length+' pts)');",
    "att(zcCuts.every(function(m){return !(m.x>35.0001&&m.x<64.9999&&m.y>35.0001&&m.y<64.9999);}),",
    "  'ZoneCuts : rien dans l îlot (35..65 apres r=5)');",
    "att(zcCuts.every(function(m){return m.x>=-0.0001&&m.x<=100.0001&&m.y>=-0.0001&&m.y<=100.0001;}),",
    "  'ZoneCuts : rien hors de la zone ext');",
    "att(zcCuts.some(function(m){return m.x>50&&m.x<64&&m.y===50;})===false,'ZoneCuts : la ligne y=50 traverse bien l îlot -> partie centrale retiree');",
    // ================= 6. faoSegClipper (affichage) =========================
    "const fn=faoSegClipper(opC,job);",
    "att(typeof fn==='function','SegClipper : fonction composee presente');",
    "const segs=[];",
    "if(typeof fn==='function')fn(0,50,1,100,50,1,function(a,b,c,d,e,f){segs.push([a,d]);});",
    "att(segs.length>0,'SegClipper : segment traverseur decoupe ('+segs.length+' morceaux)');",
    "att(segs.every(function(s){return !(s[0]<34.9999&&s[1]>65.0001);}),",
    "  'SegClipper : aucun morceau ne traverse l îlot (35..65)');",
    "let sIn=true;",
    "if(typeof fn==='function'){const probe=[];",
    "  fn(45,50,1,55,50,1,function(a,b,c,d,e,f){probe.push([a,d]);});",
    "  sIn=(probe.length===0);}",
    "att(sIn,'SegClipper : coupe interieure a l îlot supprimee');",
    "att(faoSegClipper({id:'z2d',toolId:'T1',type:'pocket'},job)===null,'SegClipper : sans zone -> null (inchange)');",
    // ================= 7. perçage : l îlot exclut les trous =================
    "const opD={id:'zd',type:'drill',toolId:'T1',pts:[[50,50],[10,10],[90,50],[30,30]],",
    "  limit:{mode:'rect',x0:0,y0:0,x1:100,y1:100,side:'center',extra:0},",
    "  limit2:{mode:'rect',x0:40,y0:40,x1:60,y1:60,extra:0}};",
    "const ptsK=faoLimitDrillPts(opD,10);",
    "const kp=ptsK.map(function(q){return q[0]+','+q[1];}).join(' ');",
    "att(ptsK.length===3,'drill : îlot exclut le trou dedans ('+ptsK.length+' restants : '+kp+')');",
    "att(ptsK.some(function(q){return q[0]===10&&q[1]===10;})&&ptsK.some(function(q){return q[0]===90&&q[1]===50;})&&ptsK.some(function(q){return q[0]===30&&q[1]===30;}),",
    "  'drill : hors îlot conserve (10,10 / 90,50 / 30,30)');",
    "const opD2={id:'zd2',type:'drill',toolId:'T1',pts:[[50,50],[10,10]],limit2:opD.limit2};",
    "att(faoLimitDrillPts(opD2,10).length===1,'drill : îlot SEUL filtre aussi');",
    // ================= 8. sig + sanitise ====================================
    "const mkL2=function(ex){const o={id:'l2',type:'pocket',ap:4,limit2:{mode:'rect',x0:0,y0:0,x1:10,y1:10,extra:0}};",
    "  if(ex)for(const k in ex)o[k]=ex[k];return o;};",
    "const oL2=mkL2(),oNL={id:'nl',type:'pocket',ap:4};",
    "att(J(faoOpSig(oL2))!==J(faoOpSig(oNL)),'sig : limit2 entre dans la cle');",
    "const oSt=mkL2();oSt.limit2.stale=true;oSt.limit2.missing=true;",
    "att(J(faoOpSig(oSt))===J(faoOpSig(mkL2())),'sig : limit2.stale/missing hors cle (comme limit)');",
    "const oBogus={id:'b',type:'pocket',limit2:{mode:'gouffre'}};",
    "const oRect={id:'r',type:'pocket',limit2:{mode:'rect',x0:10,y0:10,x1:0,y1:0,extra:'x'}};",
    "const oCh={id:'c',type:'pocket',limit2:{mode:'chain',loop:[[0,0],[1,0],[1,1]],side:'in',extra:'y'}};",
    "const oOther={id:'o',type:'drill',limit2:{mode:'rect',x0:0,y0:0,x1:1,y1:1}};",
    "faoSanitiseOps({ops:[oBogus,oRect,oCh,oOther]});",
    "att(!oBogus.limit2,'sanitise : mode inconnu purge');",
    "att(oRect.limit2&&oRect.limit2.x0===0&&oRect.limit2.x1===10&&oRect.limit2.y0===0&&oRect.limit2.y1===10&&oRect.limit2.extra===0,",
    "  'sanitise : rect reordonne + extra numerote ('+(oRect.limit2?oRect.limit2.x0+'..'+oRect.limit2.x1:'purge')+')');",
    "att(oCh.limit2&&oCh.limit2.side==='out'&&oCh.limit2.extra===0,'sanitise : chaine force side=out + extra=0');",
    "att(oOther.limit2&&oOther.limit2.side!=='in','sanitise : (drill rect garde ses cotes)');",
    // ================= 9. fiche : rangée Zone int. ==========================
    "const all=function(root){const out=[];(function w(n){out.push(n);(n.children||[]).forEach(w);})(root);return out;};",
    "const txt=function(root){return all(root).map(function(n){return String(n.textContent||'');}).join('|');};",
    "const opU={id:'u',type:'pocket',ap:4,ae:5,ztop:18,zbot:4,x0:0,y0:0,x1:10,y1:10,toolId:'T1'};",
    "const cardU=faoOpCardElement(faoSetup(),opU,0);",
    "att(/Zone int\\./.test(txt(cardU)),'fiche : rangée Zone int. presente');",
    "const z2Sel=all(cardU).filter(function(n){return n.tagName==='SELECT'&&",
    "  Array.prototype.map.call(n.children||[],function(o){return String(o.textContent||'');}).join('|').indexOf('Rectangle (îlot)')>=0;})[0];",
    "att(!!z2Sel,'fiche : selecteur Zone int. present');",
    "if(z2Sel){",
    "  att(z2Sel.value==='none','fiche : par defaut Aucune ('+z2Sel.value+')');",
    "  att(!/Marge/.test(txt(cardU)),'fiche : pas de Marge tant que pas d îlot');",
    "  z2Sel.value='rect';z2Sel.onchange();",
    "  att(opU.limit2&&opU.limit2.mode==='rect','fiche : Rectangle ecrit op.limit2');",
    "  att(isFinite(+opU.limit2.x0)&&opU.limit2.x1>opU.limit2.x0,'fiche : rectangle initial valide');",
    "  const cardR=faoOpCardElement(faoSetup(),opU,0);",
    "  att(/Marge/.test(txt(cardR)),'fiche : Marge affichee avec l îlot');",
    "  const nbM=all(cardR).filter(function(n){return String(n.textContent||'').trim()==='Marge';}).length;",
    "  att(nbM===1,'fiche : une seule rangée Marge (îlot seul) ('+nbM+')');",
    "  z2Sel.value='chain';",
    "  z2Sel.onchange();",
    "  att(opU.limit2&&opU.limit2.mode==='chain','fiche : Chaîne ecrit op.limit2 (boucle a saisir)');",
    "  z2Sel.value='none';z2Sel.onchange();",
    "  att(!opU.limit2,'fiche : Aucune supprime op.limit2');",
    "}else att(false,'fiche : selecteur Zone int. absent');",
    // --- validation chaîne2 (îlot) + re-brançage des ancres
    "const st=faoSetup();",
    "const opK=faoOpDefaults('pocket');opK.id='k1';",
    "st.ops=st.ops||[];st.ops.push(opK);",
    "const mkE=function(a,b){return {mid:[(a[0]+b[0])/2,(a[1]+b[1])/2,0],",
    "  pts:[[a[0],a[1],0],[b[0],b[1],0]],len:Math.hypot(b[0]-a[0],b[1]-a[1]),sharp:true};};",
    "const E=[mkE([0,0],[20,0]),mkE([20,0],[20,20]),mkE([20,20],[0,20]),mkE([0,20],[0,0])];",
    "faoChainMode={setupId:st.id,opId:opK.id,edges:E,seeds:[0,2],sel:[0,1,2,3],kind:'chain2',tangent:true};",
    "faoChainOk();",
    "const LK=opK.limit2;",
    "att(LK&&LK.mode==='chain','chain2 OK : op.limit2 ecrit');",
    "att(LK&&LK.side==='out','chain2 OK : règle outil îlot forcee side=out');",
    "att(LK&&(LK.loop||[]).length>=3&&LK.closed!==undefined,'chain2 OK : boucle '+((LK&&LK.loop)||[]).length+' pts');",
    "att(LK&&LK.anchors&&LK.anchors.length===2&&LK.stale===false,'chain2 OK : 2 ancres + stale=false');",
    "att(!opK.limit,'chain2 OK : la zone ext reste vide');",
    "let r1={};try{r1=faoChainRematch(opK,E,'limit2');}catch(e){r1={err:e.message};}",
    "att(r1.changed===false&&r1.stale===false&&r1.matched===2,'rematch : memes aretes -> boucle identique, pas de stale');",
    "const E5=E.map(function(e){const m={mid:[e.mid[0]+5,e.mid[1],e.mid[2]],pts:[[e.pts[0][0]+5,e.pts[0][1],0],[e.pts[1][0]+5,e.pts[1][1],0]],len:e.len,sharp:true};return m;});",
    "let r2={};try{r2=faoChainRematch(opK,E5,'limit2');}catch(e){r2={err:e.message};}",
    "att(r2.changed===true&&r2.stale===false,'rematch : aretes deplacees de 5 (<tol 10) -> boucle re-suivie');",
    "const E99=E.map(function(e){const m={mid:[e.mid[0]+99,e.mid[1],e.mid[2]],pts:[[e.pts[0][0]+99,e.pts[0][1],0],[e.pts[1][0]+99,e.pts[1][1],0]],len:e.len,sharp:true};return m;});",
    "let r3={};try{r3=faoChainRematch(opK,E99,'limit2');}catch(e){r3={err:e.message};}",
    "att(r3.stale===true,'rematch : aretes perdues (>tol) -> îlot en stale (alerte fiche + export)');",
    "st.ops=st.ops.filter(function(o){return o.id!=='k1';});",
    // ================= 10. dispatch complet avec îlot =======================
    // La fixture n'usine qu'à l'intérieur de la poche x[10,70] y[10,50] :
    // l'îlot doit tomber DEDANS la poche pour qu'on puisse prouver le retrait.
    "const FV=[[0,0,0],[80,0,0],[80,60,0],[0,60,0],",
    " [0,0,18],[80,0,18],[80,60,18],[0,60,18],",
    " [10,10,4],[70,10,4],[70,50,4],[10,50,4],",
    " [10,10,18],[70,10,18],[70,50,18],[10,50,18],",
    " [0,10,18],[80,10,18],[80,50,18],[0,50,18]];",
    "const FT=[[0,2,1],[0,3,2],",
    " [0,1,5],[0,5,4],[2,3,7],[2,7,6],",
    " [0,4,16],[0,16,19],[0,19,7],[0,7,3],",
    " [1,2,6],[1,6,18],[1,18,17],[1,17,5],",
    " [4,5,17],[4,17,13],[4,13,12],[4,12,16],",
    " [6,7,19],[6,19,15],[6,15,14],[6,14,18],",
    " [16,12,15],[16,15,19],[13,17,18],[13,18,14],",
    " [8,9,10],[8,10,11],",
    " [8,13,9],[8,12,13],[10,15,11],[10,14,15],",
    " [8,11,15],[8,15,12],[9,13,14],[9,14,10]];",
    "const FR={v:FV,t:FT};",
    "const BX={x0:-5,y0:-5,x1:85,y1:65};",
    "const baseD=function(id,extra){const o={id:id,on:true,toolId:'T1',type:'rough3d',ztop:18,zbot:4,ap:4,ae:5,radial:0.5,axial:0.5,minipasses:0};",
    "  if(extra)for(const k in extra)o[k]=extra[k];return o;};",
    "const keepAM=faoActiveMesh;",
    "faoActiveMesh=function(){return {mesh:FR,box:BX};};",
    // reference SANS îlot : l'îlot candidat est bien usiné (sinon « rien a retirer »)
    "const opB0=baseD('d0');job.ops=[opB0];",
    "let mvB=[];",
    "try{mvB=faoOpMoves(opB0,job);}catch(e){att(false,'dispatch base : exception '+e.message);}",
    "const cB=mvB.filter(function(m){return !m.r;});",
    // avec îlot au centre de la poche
    "const opR=baseD('d1',{limit2:{mode:'rect',x0:30,y0:20,x1:50,y1:40,extra:0}});",
    "job.ops=[opR];",
    "let mvD=[];",
    "try{mvD=faoOpMoves(opR,job);}catch(e){att(false,'dispatch îlot : exception '+e.message);}",
    "finally{faoActiveMesh=keepAM;}",
    "const cD=mvD.filter(function(m){return !m.r;});",
    "att(cD.length>500,'dispatch îlot : parcours genere ('+cD.length+' coupes)');",
    "const R2d=faoLimit2R(opR.limit2,10);",
    "const inR2=function(m){return m.x>R2d.x0+1e-6&&m.x<R2d.x1-1e-6&&m.y>R2d.y0+1e-6&&m.y<R2d.y1-1e-6;};",
    "const outR2=function(m){return m.x<R2d.x0-1e-6||m.x>R2d.x1+1e-6||m.y<R2d.y0-1e-6||m.y>R2d.y1+1e-6;};",
    "const inPocket=function(m){return m.x>10&&m.x<70&&m.y>10&&m.y<50;};",
    "const baseIn=cB.filter(function(m){return !m.ent&&inR2(m);}).length;",
    "att(baseIn>10,'dispatch : sans îlot, la zone de l îlot est bien usinee ('+baseIn+' coupes)');",
    "const dedans=cD.filter(inR2);",
    "att(dedans.length===0,'dispatch îlot : '+(dedans.length?dedans.length+' coupes dans l îlot !':'aucune coupe dans l îlot '+(R2d.x0)+'..'+(R2d.x1)));",
    "const baseKeep=cB.filter(function(m){return !m.ent&&inPocket(m)&&outR2(m);}).length;", // 007/09-09 : entrées (ent) hors comparaison
    "const keepD=cD.filter(function(m){return !m.ent&&inPocket(m)&&outR2(m);}).length;",
    // 10-09-002 : les entrées (lever/rapide/plongée plate, arcs circ) varient
    // selon l'ordre du parcours — les comptes de mouvements divergent sans
    // que l'usinage change (constaté : comptes 663/1414 mais toutes les
    // extras sont à ≤1,4 mm d'une cote de base). L'invariant réel : TOUTES
    // les cotes usinées par la base le sont aussi avec l'îlot (inclusion
    // géométrique des XY de coupe), et rien dans l'îlot (dedans=0 ci-dessus).
    "const gxy=function(a){const s=new Set();a.forEach(function(m){if(!m.r&&inPocket(m)&&outR2(m))s.add((Math.round(m.x*10)/10)+','+(Math.round(m.y*10)/10));});return s;};",
    "const gb=gxy(cB),gd=gxy(cD);let onlyB=0,onlyD=0;gb.forEach(function(k){if(!gd.has(k))onlyB++;});gd.forEach(function(k){if(!gb.has(k))onlyD++;});",
    "att(gb.size>10&&onlyB===0,'dispatch îlot : usinage conserve autour (toutes les cotes de la base refaites ; seules entrees/islet en plus : onlyDispatch '+onlyD+')');",
    // rapport
    "p('limit2 rect k=r+marge : '+R1.x0+'..'+R1.x1+' | clip rect '+cutsOut.length+' pts | clip chaine '+cutsP.length+' pts');",
    "p('ZoneCuts '+zcCuts.length+' pts | SegClipper '+segs.length+' morceaux | drill '+(ptsK.length)+' trous');",
    "p('dispatch îlot : '+cD.length+' coupes, 0 dedans, non-ent keep '+keepD+' vs base '+baseKeep+' | geo xy base '+gb.size+' dispatch '+gd.size+' | onlyBase '+onlyB+' onlyDispatch '+onlyD);",
    "if(ATT.length){p('');p('ECHECS ('+ATT.length+') :');ATT.forEach(function(m){p('  x '+m);});}",
    "else p('TOUT EST CONFORME');",
    "return P.join(String.fromCharCode(10));"
  ].join('\n');
  const r=await vm.runInContext('(async()=>{'+R+'})()',ctx,{filename:'fao_zone2.js'});
  console.log(r);
  process.exit(/ECHECS|  x /.test(r)?1:0);
})().catch(e=>{console.error('ECHEC',String((e&&e.message)||e).slice(0,500));process.exit(1);});
